### ISSUE TITLE
README 说明修改建议

### ISSUE THREAD

**Issue by DonaldGuo** [zyslife/react-native-head-tab-view#1]
npm install @react-native-community/viewpager --save
这一步建议在README里仿照其他rn库说明添加手动导入说明(或者引导去看@react-native-community/viewpager github README的导入说明)

以及针对安卓端下使用@react-native-community/viewpager版本, 做个说明, :
2.x版本是用的Android support可用于rn0.59以下版本
3.x版本是用的AndroidX的, 可用于rn0.60以上版本

**Comment by zyslife** [comment]
已修改

**Comment by zyslife** [comment]
已修改 @DonaldGuo
