### ISSUE TITLE
 Example 点击后崩溃报错

### ISSUE THREAD

**Issue by zhenghao-z** [zyslife/react-native-head-tab-view#102]
## Example 点击后崩溃报错
clone项目，cd example,  yarn, yarn run android, example应用可以启动，但是点击任意一个示例，都会报这个错

TypeError: undefined is not a function

This error is located at:
    in ForwardRef(GestureContainer) (at createHeaderTabsComponent.tsx:39)
    in CollapsibleHeaderTabView (at createHeaderTabsComponent.tsx:12)
    in ForwardRef (at TabViewBase.tsx:93)
    in TabViewContainer (at ExampleBasic.tsx:19)
    in RCTView (at View.js:34)
    in View (at ExampleBasic.tsx:14)
    in ExampleBasic (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:573)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in RCTView (at View.js:34)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:623)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:84)
    in MaybeScreen (at CardStack.tsx:616)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:54)
    in MaybeScreenContainer (at CardStack.tsx:498)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in SafeAreaConsumer (at StackView.tsx:456)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:50)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaConsumer (at SafeAreaProviderCompat.tsx:32)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in GestureHandlerRootView (at GestureHandlerRootView.android.tsx:26)
    in GestureHandlerRootView (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at Example.tsx:23)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:409)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at Example.tsx:21)
    in Example (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39), js engine: hermes

## Package versions  

- React:
- React Native:
- React-Native-Gesture-Handler

**Comment by zyslife** [comment]
@zhenghao-z 我尝试是可以正常点击进去的，你是否开了debug呢

**Comment by zhenghao-z** [comment]
> @ zhenghao-z我尝试是可以正常点击进去的，你是否开了debug呢

没有开debug, 我拉了两次都是这个问题，我同事那边也是一样的问题

**Comment by zyslife** [comment]
@zhenghao-z 试试download zip呢，因为我这边试过几次了，都是正常的，你有通过镜像clone吗. 另外试试ios呢

**Comment by zyslife** [comment]
@zhenghao-z 我知道了，你把react-native-reanimated版本先控制在v2.1.0吧，我等会适配下最新版本。

**Comment by zyslife** [comment]
@zhenghao-z 最新代码已修改，请再尝试看看。

**Comment by zhenghao-z** [comment]
> @zhenghao-z 最新代码已修改，请再尝试看看。

刚试了下，可以了， tks ，
要是下方列表抖动的问题能解决就完美了 ，
