### ISSUE TITLE
严重的一个bug

### ISSUE THREAD

**Issue by xiaoxiaodemeng** [zyslife/react-native-head-tab-view#103]
版本都是最新的

例子可以是demo

操作：

疯狂的页面切换到---这个库形成的页面，多次之后 App直接卡死闪退

**Comment by xiaoxiaodemeng** [comment]
https://user-images.githubusercontent.com/30209304/120056873-8cbd8480-c071-11eb-96f8-d9afcaf524a3.mp4

这个是视频

**Comment by xiaoxiaodemeng** [comment]
快速操作只是为了 快一点达到那个点，应该是内存炸了

**Comment by zyslife** [comment]
不是内存溢出问题，应该是操作了已经不存在的view，我排查下。

**Comment by zyslife** [comment]
@xiaoxiaodemeng 在v4.0.0-rc11修改了，可以验证下。

**Comment by xiaoxiaodemeng** [comment]
感觉上是可以的，这说明应该有效果，等我后面再多试试，再看看会不会再有崩溃

**Comment by xiaoxiaodemeng** [comment]
原先我这有个场景，页面挺复杂的集成了这个库，进去页面的瞬间，快速返回，必崩溃，view找不到了，现在没有了

**Comment by zyslife** [comment]
应该是不会出现这个问题了，如果再有问题记得联系我。

**Comment by zyslife** [comment]
如果还有问题，再重新打开。
