### ISSUE TITLE
I am getting unable to resolve react native-reanimated module

### ISSUE THREAD

**Issue by prateekpareekvyas** [zyslife/react-native-head-tab-view#104]
reanimated 2 failed to create a worklet, maybe you forgot to add reanimated’s babel plugin

i am getting this error i have include plugin also

module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin' ]
};

**Comment by zyslife** [comment]
> reanimated 2 failed to create a worklet, maybe you forgot to add reanimated’s babel plugin
> 
> i am getting this error i have include plugin also
> 
> module.exports = {
> presets: ['module:metro-react-native-babel-preset'],
> plugins: ['react-native-reanimated/plugin' ]
> };

Do you attempt to execute?
```
npm start -- --reset-cache
```

**Comment by prateekpareekvyas** [comment]
yes can we use this library with react-native cli

**Comment by zyslife** [comment]
> yes i have done npm start -- --reset-cache .... can we use this library with react-native cli

Can you run the [Example](https://github.com/zyslife/react-native-head-tab-view/tree/master/Example) project successfully?
This library cannot be run with react-native cli.

**Comment by prateekpareekvyas** [comment]
ok i was using this library with React native cli
