### ISSUE TITLE
库中是含有原生代码吗？存RN包运行报错

### ISSUE THREAD

**Issue by xiaopian** [zyslife/react-native-head-tab-view#105]
<img width="393" alt="image" src="https://user-images.githubusercontent.com/8142743/120458592-fae3ad80-c3c9-11eb-8c0e-561f86662574.png">

**Comment by zyslife** [comment]
react-native-gesture-handler react-native-reanimated  这两个库都是有包含原生代码的。
你是运行的Example还是你自己的项目？
@xiaopian

**Comment by xiaopian** [comment]
> react-native-gesture-handler react-native-reanimated 这两个库都是有包含原生代码的。
> 你是运行的Example还是你自己的项目？
> @xiaopian

自己的项目

**Comment by zyslife** [comment]
@xiaopian  你好，请问现在还有问题吗？
