### ISSUE TITLE
ios v3 tab左右切换 tabSence会闪动问题 

### ISSUE THREAD

**Issue by coldrainc** [zyslife/react-native-head-tab-view#106]
## Package versions  

- React: 0.6
- React Native: 16.8.6
- React-Native-Gesture-Handler：1.4.1
试了很多次，发现不是特定系统和 组件到导致的。安卓 ios 都会出现。在有内容的情况下，左右切换tab都会出现闪一下的情况

**Comment by zyslife** [comment]
> ## Describe the bug
> 
> 
> 
> ### Expected behavior
> 
> 
> 
> ## Package versions  
> 
> 
> 
> 
> 
> - React: 0.6
> 
> - React Native: 16.8.6
> 
> - React-Native-Gesture-Handler：1.4.1
> 
> 试了很多次，发现不是特定系统和 组件到导致的。安卓 ios 都会出现。在有内容的情况下，左右切换tab都会出现闪一下的情况

你好，不添加可折叠头部，单纯使用原tab组件会有这情况吗？

**Comment by coldrainc** [comment]
找到原因了，按照给的例子封了一个组件。sceneMap 传的匿名函数导致的。我自己的用法错误

**Comment by zyslife** [comment]
> 找到原因了，按照给的例子封了一个组件。sceneMap 传的匿名函数导致的。我自己的用法错误，导致组件更新都会销毁重建

好的。
