### ISSUE TITLE
触摸事件，列表滚动停止

### ISSUE THREAD

**Issue by songxiaoliang** [zyslife/react-native-head-tab-view#11]
当从列表向上滑动到头部区域， 当列表在滚动缓冲时， 再次触摸头部区域， 要使其列表立刻停止滚动。就像单纯当列表一样，这块还需要处理。

**Comment by zyslife** [comment]
@songxiaoliang   已修复，版本 v1.1.1

**Comment by songxiaoliang** [comment]
@zyslife 你好，刚才测试依然没有解决该问题。再重复下问题吧：当从底部列表向上滑动时， 在列表滑动过程中（还没有停止），滑动区域到Header部分，触摸屏幕， 需要让列表停止滚动。

**Comment by zyslife** [comment]
> 当从列表向上滑动到头部区域， 当列表在滚动缓冲时， 再次触摸头部区域， 要使其列表立刻停止滚动。就像单纯当列表一样，这块还需要处理。

我明白了，我明天看看
