### ISSUE TITLE
我想切换flatlist为biglist，如何更换？

### ISSUE THREAD

**Issue by z5614036** [zyslife/react-native-head-tab-view#111]
https://github.com/marcocesarato/react-native-big-list，这个性能比flatlist好，但目前看没有提供接入的口

**Comment by zyslife** [comment]
> https://github.com/marcocesarato/react-native-big-list，这个性能比flatlist好，但目前看没有提供接入的口

你好，我抽时间评估完后给你回复。

**Comment by zyslife** [comment]
@z5614036 很抱歉，我回复的有点晚了，结论是目前没办法去替换，因为`const ref = useAnimatedRef()`，我需要将ref设置到ScrollView上，我刚看了下bigList的源码，没法办到。
