### ISSUE TITLE
flatlist scroll back to start unexpectedly

### ISSUE THREAD

**Issue by surethink** [zyslife/react-native-head-tab-view#115]
## Describe the bug
after scroll down some distance,  when I tap the screen or try to scroll, the flatlist scroll back to start immediately 

### Expected behavior

don't scroll to start unexpectedly as the video shows
https://user-images.githubusercontent.com/23416921/130540636-9c231635-473c-4b38-b0b3-8fc55e793f89.mov

## Package versions  

- React:17.0.2
- React Native:0.64
- React-Native-Gesture-Handler

**Comment by zyslife** [comment]
@surethink  Why isn't the header of the page moving?

**Comment by surethink** [comment]
> @surethink Why isn't the header of the page moving?

sorry for late reply. the issue have not happen again, maybe it's fixed when I fix other bugs of my program
