### ISSUE TITLE
How catch event onScoll or onScollEnd etc of HScrollview

### ISSUE THREAD

**Issue by kulehung** [zyslife/react-native-head-tab-view#116]
## Describe the bug
I push a Flashlist in Hscrollview 
Scroll in Hscrollview working first however I not catch event this scroll
### Expected behavior
catch event onScoll or onScollEnd etc of HScrollview
## Package versions  

- React: "16.13.1"
- React Native: "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz"
- React-Native-Gesture-Handler: "^1.10.3"

**Comment by zyslife** [comment]
You can get an animated object using the `makeScrollTrans` function.
Perhaps you can learn more about the use of this function by using this [example](https://github.com/zyslife/react-native-head-tab-view/blob/master/Example/src/ExampleHeaderAnimated.tsx).
