### ISSUE TITLE
renderScrollHeader这个组件内的元素无法点击，有临时解决方案吗

### ISSUE THREAD

**Issue by spokeen** [zyslife/react-native-head-tab-view#12]

**Comment by zyslife** [comment]
@spokeen 已修复，版本 v1.1.1

**Comment by spokeen** [comment]
> @spokeen 已修复，版本 v1.1.1

我看了下源码，具体原因是因为 TabView.js 中 的_renderContent() 中内容盖住了部分renderScrollHeader()内容，所以renderScrollHeader中上半部分可以点击，但下半部分无法点击，
但是用 v1.1.1版本的看了，貌似还是不行

**Comment by zyslife** [comment]
> > @spokeen 已修复，版本 v1.1.1
> 
> 
> 
> 我看了下源码，具体原因是因为 TabView.js 中 的_renderContent() 中内容盖住了部分renderScrollHeader()内容，所以renderScrollHeader中上半部分可以点击，但下半部分无法点击，
> 
> 但是用 v1.1.1版本的看了，貌似还是不行



有设置这个属性吗headerRespond？

**Comment by spokeen** [comment]
@zyslife  加了headerRespond后，就可以点击了，谢谢你帮助

哪里有洞，没脸见人了 。
