### ISSUE TITLE
This plugin is not applicable to @react-navigation/native-stack

### ISSUE THREAD

**Issue by bojianyin** [zyslife/react-native-head-tab-view#128]
## When it is just opened, it can work normally. When the viewpager has two, I scroll the first screen to the middle, and then slide to the second screen. At this time, the scroll distance of the second screen is 0, and then scroll down. At this time, I slide to the first screen, and the problem reappears.

**After I changed to @react-navigation/native-stack, there was no problem, because the official example used @react-navigation/native-stack. I checked this problem for a long time. It turned out that I used @react-navigation/native-stack**

## Package versions  

- React:17.0.2
- React Native:0.65.1
- React-Native-Gesture-Handler：2.1.0
- @react-navigation/native-stack：6.1.0

**Comment by bojianyin** [comment]
I am very sure that it is an existing bug. I hope the author can fix it, because this library is a very good solution for reactnative to implement Scrollview + viewpager. Thank you very much for providing such a tool. Thank you

**Comment by zyslife** [comment]
@bojianyin Thank you very much for your attention. Can you provide a simple project to demonstrate this problem?

**Comment by bojianyin** [comment]
Tomorrow or the day after tomorrow, I will provide a demo of problem recurrence

**Comment by bojianyin** [comment]
https://user-images.githubusercontent.com/26374588/147622417-f45bebf9-ba3d-4007-82f0-98a91d3590ae.mp4

@zyslife Hello, author, I have uploaded the demo case that can reproduce this error to my warehouse address. Please help troubleshoot the problem and fix the bug as soon as possible. Thank you very much!  
see -> [https://github.com/bojianyin/headtabviewdemobug.git](url)

**Comment by bojianyin** [comment]
click here @zyslife  😂😂😂 [https://github.com/bojianyin/headtabviewdemobug.git](https://github.com/bojianyin/headtabviewdemobug.git)

**Comment by zyslife** [comment]
@bojianyin I have tried your demo on `iOS` and everything is normal. I haven't had time to test it on `Android` yet. I think I will do it tomorrow.
I guess `React-Native-Gesture-Handler` is not enabled properly.I'll get a final verdict after I test it on Android tomorrow, but before that you can try to check if `React-Native-Gesture-Handler` works.

**Comment by zyslife** [comment]
@bojianyin The reason is that `react-navigation6` is incompatible with `React-Native-Gesture-Handler` . [same issue](https://github.com/software-mansion/react-native-gesture-handler/issues/1478#issuecomment-1000062141)

**Comment by bojianyin** [comment]
@zyslife Thanks for the author's attention. It's really because of this. The problem has been solved. Thank you
