### ISSUE TITLE
头部很长的时候，点击和下拉刷新共存吗？

### ISSUE THREAD

**Issue by rockstone001** [zyslife/react-native-head-tab-view#13]

**Comment by rockstone001** [comment]
我这边有个场景，在头部很长的时候 也需要 整体 下拉 可以刷新，哪怕只需要头部的弹性下拉 自己获取刷新事件 都可以？目前这个组件 可以支持吗？

**Comment by zyslife** [comment]
> 我这边有个场景，在头部很长的时候 也需要 整体 下拉 可以刷新，哪怕只需要头部的弹性下拉 自己获取刷新事件 都可以？目前这个组件 可以支持吗？
> 
> 

目前不支持下拉刷新，后面可能会考虑扩展
