### ISSUE TITLE
组件兼容性问题

### ISSUE THREAD

**Issue by wyrainmonkey** [zyslife/react-native-head-tab-view#134]
## Describe the bug
咱们的组件仅支持系统的ScrollView，sectionList ，flatlist 吗 
我现在用了一个第三方的瀑布流组件  import { StaggeredList } from 'react-native-staggered-list'
这个组件也是用VirtualizedList 封装的，
const HSStaggeredList = HPageViewHoc(StaggeredList)
现在是报需要用Component 继承的组件,这个组件是泛型的，请问该怎么改

### Expected 

- [ ] behavior

## Package versions  

- React:
- React Native: 
- React-Native-Gesture-Handler

**Comment by wyrainmonkey** [comment]
this._scrollView.setNativeProps is not a function 报这个错误

**Comment by zyslife** [comment]
> this._scrollView.setNativeProps is not a function 报这个错误

你好，目前是只支持ScrollView，sectionList ，flatlist，因为其他列表组件或多或少会出现兼容问题，如果你感兴趣，可以尝试去fork修改，提交mr，期待你的加入。

**Comment by wyrainmonkey** [comment]
请问为什么debug的时候就卡死那，在进入到你写的吸顶界面的时候，在首页的时候是能debug的进入到吸顶界面就会卡死
