### ISSUE TITLE
onRefresh not working

### ISSUE THREAD

**Issue by manhhoang02** [zyslife/react-native-head-tab-view#144]
## Describe the bug
when i use props onRefresh and refreshing in HFlatList, it is very difficult to scroll up and down.
## Package versions  

- React: "18.1.0"
- React Native: "0.70.2"
- React-Native-Gesture-Handler: "^2.12.0"

**Comment by manhhoang02** [comment]
https://github.com/zyslife/react-native-head-tab-view/assets/91677571/a3a7f0fe-ad46-40f8-8b0c-012b20ae3cd5

**Comment by Abbaskatariya** [comment]
how did you fix this issue ?
