### ISSUE TITLE
TypeError: Cannot read property 'scrollTo' of null

### ISSUE THREAD

**Issue by GitHub-hyj** [zyslife/react-native-head-tab-view#16]
您好，用了您的框架后报错了。
TypeError: Cannot read property 'scrollTo' of null
请问怎么解决？

**Comment by zyslife** [comment]
请参考Example2.tsx的getNode()
this.mFlatlist.getNode().scrollToOffset({ offset: 0, animated: true })

@GitHub-hyj

**Comment by GitHub-hyj** [comment]
谢谢您的回复。
还有一个问题，我写了一个View做自定义导航栏（写在tableView之前），但是tableView的层级高于导航栏，向上滚动的时候导航栏会被tableView挡住。请问这个怎么解决，我试过加zIndex，elevation属性，但是都没用。

**Comment by zyslife** [comment]
> 谢谢您的回复。
> 
> 还有一个问题，我写了一个View做自定义导航栏（写在tableView之前），但是tableView的层级高于导航栏，向上滚动的时候导航栏会被tableView挡住。请问这个怎么解决，我试过加zIndex，elevation属性，但是都没用。

你可以尝试让 自定义导航绝对定位，然后布局在tableView后面

**Comment by GitHub-hyj** [comment]
> > 谢谢您的回复。
> > 还有一个问题，我写了一个View做自定义导航栏（写在tableView之前），但是tableView的层级高于导航栏，向上滚动的时候导航栏会被tableView挡住。请问这个怎么解决，我试过加zIndex，elevation属性，但是都没用。
> 
> 你可以尝试让 自定义导航绝对定位，然后布局在tableView后面

试过了。但是tableView也要绝对定位和计算高度，不是很方便

**Comment by zyslife** [comment]
> > > 谢谢您的回复。
> > > 还有一个问题，我写了一个View做自定义导航栏（写在tableView之前），但是tableView的层级高于导航栏，向上滚动的时候导航栏会被tableView挡住。请问这个怎么解决，我试过加zIndex，elevation属性，但是都没用。
> > 
> > 
> > 你可以尝试让 自定义导航绝对定位，然后布局在tableView后面
> 
> 试过了。但是tableView也要绝对定位和计算高度，不是很方便

```
<View style={{ flex: 1, backgroundColor: '#FFF' }}>
       <View style={{ width: '100%', height: 50, backgroundColor: 'red', zIndex: 11 }} />
             <TabView
                    tabs={this.state.tabs}
                    renderScene={this._renderScene}
                    makeHeaderHeight={() => { return HEAD_HEIGHT }}
                    renderScrollHeader={this._renderScrollHeader}
               />
</View>
```
尝试加一个zIndex:11

**Comment by GitHub-hyj** [comment]
> > > > 谢谢您的回复。
> > > > 还有一个问题，我写了一个View做自定义导航栏（写在tableView之前），但是tableView的层级高于导航栏，向上滚动的时候导航栏会被tableView挡住。请问这个怎么解决，我试过加zIndex，elevation属性，但是都没用。
> > > 
> > > 
> > > 你可以尝试让 自定义导航绝对定位，然后布局在tableView后面
> > 
> > 
> > 试过了。但是tableView也要绝对定位和计算高度，不是很方便
> 
> ```
> <View style={{ flex: 1, backgroundColor: '#FFF' }}>
>        <View style={{ width: '100%', height: 50, backgroundColor: 'red', zIndex: 11 }} />
>              <TabView
>                     tabs={this.state.tabs}
>                     renderScene={this._renderScene}
>                     makeHeaderHeight={() => { return HEAD_HEIGHT }}
>                     renderScrollHeader={this._renderScrollHeader}
>                />
> </View>
> ```
> 
> 尝试加一个zIndex:11

在大佬的帮助下终于解决了问题。谢谢
