### ISSUE TITLE
滚动跳跃

### ISSUE THREAD

**Issue by wuazhu** [zyslife/react-native-head-tab-view#19]
gif 图太大了, 传到cdn 了,  https://imgs.wuazhu.cn/imgs/Kapture%202020-06-28%20at%2017.58.50_quaL8n.gif

问题: 如何固定滚动的生效区域, 就是我看 demo 的下拉加载都是在 tabbar 以下开始, 我的菊花都是从页面顶部开始, 这个是否跟 makeHeaderHeight 设置有关? 另一个页面的makeHeaderHeight是 200, 但是加载也是从页面顶部开始. 

另一个是会产生连带滚动, 并且需要再次拖动才能回到原位

代码如下:
```js
<TabView
      tabs={tabs}
      makeHeaderHeight={() => 44}
      activeTextStyle={{ color: '#333', fontSize: 22, fontWeight: '900' }}
      inactiveTextStyle={{ color: '#999', fontSize: 22, }}
      averageTab={false}
      renderScene={_renderScene}
      renderTabBar={(tabbarProps) => (
        <Tabbar
          {...tabbarProps}
          underLineHidden={true}
          style={{ borderBottomWidth: 0, }}
        />
      )}
      renderScrollHeader={() => <SearchInput style={{ height: 44 }} />}>
    </TabView>
```

**Comment by zyslife** [comment]
> gif 图太大了, 传到cdn 了,  https://imgs.wuazhu.cn/imgs/Kapture%202020-06-28%20at%2017.58.50_quaL8n.gif
> 
> 
> 
> 问题: 如何固定滚动的生效区域, 就是我看 demo 的下拉加载都是在 tabbar 以下开始, 我的菊花都是从页面顶部开始, 这个是否跟 makeHeaderHeight 设置有关? 另一个页面的makeHeaderHeight是 200, 但是加载也是从页面顶部开始. 
> 
> 
> 
> 另一个是会产生连带滚动, 并且需要再次拖动才能回到原位
> 
> 
> 
> 代码如下:
> 
> ```js
> 
> <TabView
> 
>       tabs={tabs}
> 
>       makeHeaderHeight={() => 44}
> 
>       activeTextStyle={{ color: '#333', fontSize: 22, fontWeight: '900' }}
> 
>       inactiveTextStyle={{ color: '#999', fontSize: 22, }}
> 
>       averageTab={false}
> 
>       renderScene={_renderScene}
> 
>       renderTabBar={(tabbarProps) => (
> 
>         <Tabbar
> 
>           {...tabbarProps}
> 
>           underLineHidden={true}
> 
>           style={{ borderBottomWidth: 0, }}
> 
>         />
> 
>       )}
> 
>       renderScrollHeader={() => <SearchInput style={{ height: 44 }} />}>
> 
>     </TabView>
> 
> ```

因为demo里面的不是下拉加载，可以具体看看代码。
目前下拉加载是会在顶部，而且效果很差。不推荐使用下拉加载。
后续我会优化这个。

**Comment by wuazhu** [comment]
> 因为demo里面的不是下拉加载，可以具体看看代码。
> 目前下拉加载是会在顶部，而且效果很差。不推荐使用下拉加载。
> 后续我会优化这个。

好的. 谢谢~

**Comment by wuazhu** [comment]
![image](https://user-images.githubusercontent.com/15375121/85947904-0dff2980-b980-11ea-989a-74a7a5796baf.png)
还有个问题,  就是在滚动的时候加入了上拉加载更多, 滚着滚着就会报这个错. 也不知道哪里引起的..

**Comment by zyslife** [comment]
Duplicate of #16

**Comment by wuazhu** [comment]
> Duplicate of #16

可是我里面并没有用到 scrollTop, 只有加了一个 listFootComponent, 展示已经到底了. 其他并未做指定滚动到某个节点或者位置.

**Comment by zyslife** [comment]
> > Duplicate of #16
> 
> 
> 
> 可是我里面并没有用到 scrollTop, 只有加了一个 listFootComponent, 展示已经到底了. 其他并未做指定滚动到某个节点或者位置.

最好是能提供一个demo让我可以查看具体问题

**Comment by zyslife** [comment]
我现在关掉这个issue，如果还有问题，请再次打开
