### ISSUE TITLE
TypeError:addListener is not a function

### ISSUE THREAD

**Issue by xtzlyp** [zyslife/react-native-head-tab-view#2]
请问下作者的rn的版本是多少，我的版本是0.57的使用后报TypeError:addListener is not a function

**Comment by zyslife** [comment]
@xtzlyp 
是否有像Example.tsx中，把 renderScene中的参数传递给下面的组件
private _renderScene = (sceneProps: { item: string, index: number }) => {
        const { item } = sceneProps;
        if (item == 'ScrollView') {
            return <Page1 {...sceneProps} />
        } else if (item == 'FlatList') {
            return <Page2 {...sceneProps} />
        } else if (item == 'SectionList') {
            return <Page3 {...sceneProps} />
        }
        return null;
    }
<HScrollView {...this.props}>
<HFlatList {...this.props}>

**Comment by xtzlyp** [comment]
是的，和您这边做的是一样的，所以我怀疑是我这边react native 的版本不对，想问下您这边正确使用该组件的时候的react native版本是多少，
addListener() {
            const { addListener, containerTrans } = this.props //应该是这行代码中addListener不存在
            addListener(this, TABVIEW_TABDIDCLICK, this.tabDidClick)
            addListener(this, TABVIEW_BECOME_RESPONDER, this.becomeResponder)
            containerTrans && containerTrans.addListener(this.updateView);
        }

**Comment by zyslife** [comment]
{
  "name": "rn057",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/viewpager": "^3.3.0",
    "react": "16.5.0",
    "react-native": "0.57.0",
    "react-native-head-tab-view": "^1.0.2"
  },
  "devDependencies": {
    "babel-jest": "25.1.0",
    "jest": "25.1.0",
    "metro-react-native-babel-preset": "0.59.0",
    "react-test-renderer": "16.5.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
@xtzlyp   我到0.57版本下测试过没有问题，我先关了这个问题了。

**Comment by aJIEw** [comment]
我也遇到了同样的问题，每次退出页面的时候都会报错，HPageViewHoc 中 [removeListener](https://github.com/zyslife/react-native-head-tab-view/blob/6d073778641e5203466915fe83de036f31034523/Example/react-native-head-tab-view/HPageViewHoc.js#L98) 好像手误少写了个 `addListener`？
```react
const { addListener, removeListener, containerTrans } = this.props
```

**Comment by zyslife** [comment]
> 我也遇到了同样的问题，每次退出页面的时候都会报错，HPageViewHoc 中 [removeListener](https://github.com/zyslife/react-native-head-tab-view/blob/6d073778641e5203466915fe83de036f31034523/Example/react-native-head-tab-view/HPageViewHoc.js#L98) 好像手误少写了个 `addListener`？
> 
> ```
> const { addListener, removeListener, containerTrans } = this.props
> ```

不好意思，确实是上次更新时手误写错了！我现在更新

**Comment by aJIEw** [comment]
@zyslife 感谢，有个问题想请教下，是否可以添加一个 TabBar 不吸顶的属性或者可配置吸顶的位置，比如 `frozeTop`，因为考虑到有些情况标题栏会覆盖在头图上面（比如透明标题栏），这样滑动到顶部的时候 TabBar 就会被标题栏覆盖。
目前我用了个比较 hack 的做法，修改 [makeTabParams](https://github.com/zyslife/react-native-head-tab-view/blob/8606366ddfd8a4dbf1bfa3b5f251bbf6c7e4de7c/Example/react-native-head-tab-view/TabView.js#L486) 的 `outputRange: [headerHeight, 1, 0]` 让 TabBar 滑动到顶部的时候继续向上滑动。不知道你有什么更好的建议吗？

**Comment by zyslife** [comment]
> @zyslife 感谢，有个问题想请教下，是否可以添加一个 TabBar 不吸顶的属性或者可配置吸顶的位置，比如 `frozeTop`，因为考虑到有些情况标题栏会覆盖在头图上面（比如透明标题栏），这样滑动到顶部的时候 TabBar 就会被标题栏覆盖。
> 目前我用了个比较 hack 的做法，修改 [makeTabParams](https://github.com/zyslife/react-native-head-tab-view/blob/8606366ddfd8a4dbf1bfa3b5f251bbf6c7e4de7c/Example/react-native-head-tab-view/TabView.js#L486) 的 `outputRange: [headerHeight, 1, 0]` 让 TabBar 滑动到顶部的时候继续向上滑动。不知道你有什么更好的建议吗？

可以，我今天晚上加上这个功能吧

**Comment by aJIEw** [comment]
> @aJIEw 我已经发布了v1.0.6版本，更新了frozeTop字段

感谢！
