### ISSUE TITLE
Tabbar 样式问题

### ISSUE THREAD

**Issue by MRGAN-J** [zyslife/react-native-head-tab-view#20]
大佬，请问我使用的  简例的例子后 
```javascript
import { HPageViewHoc, TabView } from 'react-native-head-tab-view'

_renderScene = (sceneProps: { item: string, index: number }) => {
        const { item } = sceneProps;
        if (item == 'ScrollView') {
            return <Page1 {...sceneProps} />
        } else if (item == 'FlatList') {
            return <Page2 {...sceneProps} />
        } else if (item == 'SectionList') {
            return <Page3 {...sceneProps} />
        }
        return null;
}
    
render() {
        return (
            <View style={{ flex: 1, backgroundColor: '#FFF' }}>
                <StatusBar
                    barStyle={'dark-content'}
                    translucent={true}
                />
                {this._renderNavBar()}
                <TabView
                        tabs={this.state.tabs}
                        renderScene={this._renderScene}
                        makeHeaderHeight={() => { return 180 }}
                        renderScrollHeader={()=><View style={{height:180,backgroundColor:'red'}}/>}
                        onChangeTab={this.onChangeTab}
                    />
            </View>
        )
    }
```

如何去掉 Tabbar 下划线或者更改下划线样式呢

**Comment by zyslife** [comment]
> 大佬，请问我使用的  简例的例子后 
> 
> ```javascript
> 
> import { HPageViewHoc, TabView } from 'react-native-head-tab-view'
> 
> 
> 
> _renderScene = (sceneProps: { item: string, index: number }) => {
> 
>         const { item } = sceneProps;
> 
>         if (item == 'ScrollView') {
> 
>             return <Page1 {...sceneProps} />
> 
>         } else if (item == 'FlatList') {
> 
>             return <Page2 {...sceneProps} />
> 
>         } else if (item == 'SectionList') {
> 
>             return <Page3 {...sceneProps} />
> 
>         }
> 
>         return null;
> 
> }
> 
>     
> 
> render() {
> 
>         return (
> 
>             <View style={{ flex: 1, backgroundColor: '#FFF' }}>
> 
>                 <StatusBar
> 
>                     barStyle={'dark-content'}
> 
>                     translucent={true}
> 
>                 />
> 
>                 {this._renderNavBar()}
> 
>                 <TabView
> 
>                         tabs={this.state.tabs}
> 
>                         renderScene={this._renderScene}
> 
>                         makeHeaderHeight={() => { return 180 }}
> 
>                         renderScrollHeader={()=><View style={{height:180,backgroundColor:'red'}}/>}
> 
>                         onChangeTab={this.onChangeTab}
> 
>                     />
> 
>             </View>
> 
>         )
> 
>     }
> 
> ```
> 
> 
> 
> 如何去掉 Tabbar 下划线或者更改下划线样式呢

可以实现renderTabBar这个方法，自定义tabbar， 实现过程可以模仿我的Tabbar

**Comment by MRGAN-J** [comment]
> > 大佬，请问我使用的  简例的例子后
> > ```js
> > import { HPageViewHoc, TabView } from 'react-native-head-tab-view'
> > 
> > 
> > 
> > _renderScene = (sceneProps: { item: string, index: number }) => {
> > 
> >         const { item } = sceneProps;
> > 
> >         if (item == 'ScrollView') {
> > 
> >             return <Page1 {...sceneProps} />
> > 
> >         } else if (item == 'FlatList') {
> > 
> >             return <Page2 {...sceneProps} />
> > 
> >         } else if (item == 'SectionList') {
> > 
> >             return <Page3 {...sceneProps} />
> > 
> >         }
> > 
> >         return null;
> > 
> > }
> > 
> >     
> > 
> > render() {
> > 
> >         return (
> > 
> >             <View style={{ flex: 1, backgroundColor: '#FFF' }}>
> > 
> >                 <StatusBar
> > 
> >                     barStyle={'dark-content'}
> > 
> >                     translucent={true}
> > 
> >                 />
> > 
> >                 {this._renderNavBar()}
> > 
> >                 <TabView
> > 
> >                         tabs={this.state.tabs}
> > 
> >                         renderScene={this._renderScene}
> > 
> >                         makeHeaderHeight={() => { return 180 }}
> > 
> >                         renderScrollHeader={()=><View style={{height:180,backgroundColor:'red'}}/>}
> > 
> >                         onChangeTab={this.onChangeTab}
> > 
> >                     />
> > 
> >             </View>
> > 
> >         )
> > 
> >     }
> > ```
> > 
> > 
> > 如何去掉 Tabbar 下划线或者更改下划线样式呢
> 
> 可以实现renderTabBar这个方法，自定义tabbar， 实现过程可以模仿我的Tabbar

好的呢，谢谢
