### ISSUE TITLE
HFlatList使用Scroll监听滚动行为出现的问题

### ISSUE THREAD

**Issue by MRGAN-J** [zyslife/react-native-head-tab-view#22]
HFlatList使用Scroll监听滚动行为出现Tabbar固定和renderScrollHeader固定
导致FlastList向上滑动时 头部和Tabbar固定在原处

**Comment by zyslife** [comment]
可以参考Example2的 
makeScrollTrans={this._makeScrollTrans}

**Comment by MRGAN-J** [comment]
> 可以参考Example2的
> makeScrollTrans={this._makeScrollTrans}

可以可以 这很大佬。谢谢^_^ 膜拜
