### ISSUE TITLE
添加renderRightView时，tab滑动状态有问题

### ISSUE THREAD

**Issue by Synaric** [zyslife/react-native-head-tab-view#23]
现象：有个需求是在tab右侧添加一个排序按钮。我添加renderRightView后，tab滑动到了Index = 1，但是位置1的tab并没有进入高亮状态。去掉renderRightView，一切正常

**Comment by zyslife** [comment]
> 现象：有个需求是在tab右侧添加一个排序按钮。我添加renderRightView后，tab滑动到了Index = 1，但是位置1的tab并没有进入高亮状态。去掉renderRightView，一切正常

我尝试是可以的，可以看看你代码例子么

**Comment by Synaric** [comment]
谢谢回复，应该是我没用对。有问题的代码已经删了，今天重写一遍居然没问题...
