### ISSUE TITLE
ScrollView.prototype undefined不兼容

### ISSUE THREAD

**Issue by ykjsw** [zyslife/react-native-head-tab-view#25]
HPageViewHoc 217行报错

`return WrappedComponent.prototype.hasOwnProperty(scrollName)`

ScrollView.prototype undefined 

环境
`"react": "16.13.1",
    "react-native": "0.63.2",`

**Comment by ykjsw** [comment]
新版本的scrollview
https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollView/ScrollView.js

旧版的
https://github.com/facebook/react-native/blob/0.61-stable/Libraries/Components/ScrollView/ScrollView.js

**Comment by zyslife** [comment]
@ykjsw 已修复，版本1.1.5

**Comment by ykjsw** [comment]
感谢，验证ok
