### ISSUE TITLE
页面结构样式错乱

### ISSUE THREAD

**Issue by fengmiaorxiaobai** [zyslife/react-native-head-tab-view#26]
当tab切换页只有少量数据时。切换页面后样式错乱。在安卓手机（华为）手机在tab首页整个页面无法滑动。麻烦请大佬看一下。 @zyslife

**Comment by fengmiaorxiaobai** [comment]
![31597399392_ pic_hd](https://user-images.githubusercontent.com/18523923/90238435-8f3f4c80-de58-11ea-8f3e-2fdb13003c9c.jpg)
![31597399392_ pic](https://user-images.githubusercontent.com/18523923/90238440-92d2d380-de58-11ea-9078-6fbe692660be.jpg)
![41597399413_ pic_thumb](https://user-images.githubusercontent.com/18523923/90238444-936b6a00-de58-11ea-80e9-0008c7db23bd.jpg)

**Comment by fengmiaorxiaobai** [comment]
![51597400313_ pic](https://user-images.githubusercontent.com/18523923/90240038-1db4cd80-de5b-11ea-919c-458eb758421f.jpg)
![61597400326_ pic_hd](https://user-images.githubusercontent.com/18523923/90240043-20172780-de5b-11ea-8adc-506284973aae.jpg)

**Comment by zyslife** [comment]
@fengmiaorxiaobai 
你好，可以提供能够复现的简单代码示例吗？
另外你rn版本是多少呢？

**Comment by fengmiaorxiaobai** [comment]
你好，我用的代码例子是大神你的。就是把假数据删除了一部分，只留了一两条，然后在安卓手机上就展示成这样了。而且数据不够一屏的时候，安卓手机当前页（SCrollView页)无法滑动。 RN版本："0.62.2",

**Comment by fengmiaorxiaobai** [comment]
你好，我用的代码例子是大神你的。就是把假数据删除了一部分，只留了一两条，然后在安卓手机上就展示成这样了。而且数据不够一屏的时候，安卓手机当前页（SCrollView页)无法滑动。 我RN版本："0.62.2"。 @zyslife

**Comment by zyslife** [comment]
> 你好，我用的代码例子是大神你的。就是把假数据删除了一部分，只留了一两条，然后在安卓手机上就展示成这样了。而且数据不够一屏的时候，安卓手机当前页（SCrollView页)无法滑动。 我RN版本："0.62.2"。 @zyslife

好的，我已经修复了，在下个版本和下拉刷新功能一起上

**Comment by fengmiaorxiaobai** [comment]
好的，感谢。。。

**Comment by zyslife** [comment]
> > 你好，我用的代码例子是大神你的。就是把假数据删除了一部分，只留了一两条，然后在安卓手机上就展示成这样了。而且数据不够一屏的时候，安卓手机当前页（SCrollView页)无法滑动。 我RN版本："0.62.2"。 @zyslife
> 
> 好的，我已经修复了，在下个版本和下拉刷新功能一起上

下拉刷新版本在安卓上还有个小问题，需要延迟几天， 已经先把这个bug在v1.1.6版本修复了

**Comment by kokweng911** [comment]
@zyslife This issue actually still persist in the latest release, tested in iOS simulator. Weird thing is it doesn't always occur, once it occurs I would have to delete the app and run `react-native run-ios` to reinstall the app, then it works properly. When this happen, the header is also not scrollable. Hope this can be solved 🙏
