### ISSUE TITLE
如何实现拉下刷新？

### ISSUE THREAD

**Issue by ykjsw** [zyslife/react-native-head-tab-view#27]
目前一个screen里最外面就是一个 tab-view ，请问有办法实现下拉刷新吗？ 谢谢

**Comment by zyslife** [comment]
近期准备实现该功能

**Comment by DreamTravelingLight** [comment]
请问可以实现上拉加载吗

**Comment by zyslife** [comment]
> 请问可以实现上拉加载吗

现在不是已经支持上拉加载了啊，使用列表组件自带的就可以

**Comment by DreamTravelingLight** [comment]
就是创建的时候const HFlatList = HPageViewHoc(FlatList)，括号里面的写成自己封装的带有刷新的FlatList会报错，是只能用FlatList吗

**Comment by zyslife** [comment]
> 就是创建的时候const HFlatList = HPageViewHoc(FlatList)，括号里面的写成自己封装的带有刷新的FlatList会报错，是只能用FlatList吗

HPageViewHoc只能传入ScrollView、FlatList、SectionList， 你可以把你自己封装的FlatList里的FlatList用HPageViewHoc(FlatList)包装一下

**Comment by DreamTravelingLight** [comment]
好的明白了，谢谢

**Comment by duxj099** [comment]
> 目前一个screen里最外面就是一个 tab-view ，请问有办法实现下拉刷新吗？ 谢谢

我用的HFlatList。FlatList是 可以通过  refreshing 和 onRefresh 实现下拉刷新。   onEndReached 实现上拉加载。
这个组件解决了我的大问题，大神太厉害了

**Comment by fangasvsass** [comment]
@duxj099  headerRespond  true 的情况下 ，header在flatlist上层 无法响应flatlist 下拉事件

**Comment by yafengHe** [comment]
> @duxj099 headerRespond true 的情况下 ，header在flatlist上层 无法响应flatlist 下拉事件

我也遇到这个问题了 你解决这个问题了吗

**Comment by star-heng** [comment]
@zyslife  
headerRespond true 的情况下 ，下拉事件加了么

**Comment by zyslife** [comment]
@star-heng @yafengHe @ykjsw @DreamTravelingLight @duxj099 
v2.0已经实现了标签页的下拉刷新功能。

**Comment by zyslife** [comment]
这个issue先关了，如果有其他问题，可以打开一个新的issue
