### ISSUE TITLE
左右滑手势冲突

### ISSUE THREAD

**Issue by Papillonnn** [zyslife/react-native-head-tab-view#28]
tabs里嵌套flatlist,flatlist每个item有点击事件，左右滑动的时候会触发点击事件，这个怎么解决

**Comment by zyslife** [comment]
import { TouchableNativeFeedback, TouchableHighlight, TouchableOpacity, TouchableWithoutFeedback } from 'react-native-gesture-handler'
可以替换解决
@Papillonnn

**Comment by Papillonnn** [comment]
真的奇怪，我用自己封装了一下TouchableOpacity的组件就不行，换成TouchableOpacity就没问题了，感谢大佬，另外希望快点支持下拉刷新的功能😀

**Comment by zyslife** [comment]
> import { TouchableNativeFeedback, TouchableHighlight, TouchableOpacity, TouchableWithoutFeedback } from 'react-native-gesture-handler'
> 可以替换解决
> @Papillonnn

同时也可以将viewpager版本固定到3.3
"@react-native-community/viewpager": "3.3.0"
