### ISSUE TITLE
当内容高度小于屏幕高度时，安卓手机（小米 MIX 2S）不显示

### ISSUE THREAD

**Issue by skyoftommy** [zyslife/react-native-head-tab-view#3]
定位代码：
https://github.com/zyslife/react-native-head-tab-view/blob/2753f7233326c89786bd8fbd33dcd21a34ae3cbd/lib/HPageViewHoc.js#L152
部分手机的内容高度和屏幕高度存在精度问题，需要四舍五入处理下：
`            if (Math.floor(contentHeight) < Math.floor(containerHeight)) {//添加占位高度 placeHeight
`

**Comment by zyslife** [comment]
@skyoftommy 好的，谢谢，1.0.3版本我改过来

**Comment by zyslife** [comment]
@skyoftommy 如果不修改if (contentHeight < containerHeight)，你可以尝试设置faultHeight 是否可以解决问题
