### ISSUE TITLE
在header上放了个播放器，全屏的时候不想让它滑动，该怎么实现呢

### ISSUE THREAD

**Issue by ShengGaoW** [zyslife/react-native-head-tab-view#31]
例如，上面header是一个播放器，当播放器播放的时候，我不让tab进行上下滚动

**Comment by zyslife** [comment]
我还是不太明白你的需求。
你是希望header里面的播放器播放时，每个标签页都不能滑动吗？

**Comment by ShengGaoW** [comment]
是的。希望可以暴露出去一个属性，可以控制整体上下滑动。

**Comment by zyslife** [comment]
@ShengGaoW 我刚更新了版本，试试v2.0.2的scrollEnabled字段
