### ISSUE TITLE
头部过长时 当在头部区域往下拉 会一直重复下拉的动作 而不是直接往下拉的效果

### ISSUE THREAD

**Issue by seasonZzl** [zyslife/react-native-head-tab-view#33]
可能描述不是很清楚 可以看视频

视频地址：
[http://guangguang.kuaifaka.com/goods/picture/20200909/1000180_1599616734_0_0_907.mp4?imageMogr2\/auto-orient\/format\/webp\/ignore-error\/1](url)

**Comment by seasonZzl** [comment]
当设置了headerRespond=true时 会出现这个问题

**Comment by zyslife** [comment]
好的，我查一下原因

**Comment by zyslife** [comment]
@seasonZzl 已修复，试试v2.0.1版本

**Comment by seasonZzl** [comment]
> @seasonZzl 已修复，试试v2.0.1版本

优秀👍
