### ISSUE TITLE
Buttons/Touchable Opacity/Pressable on the bottom half of renderHeader doesn't receive onPress event

### ISSUE THREAD

**Issue by Harin329** [zyslife/react-native-head-tab-view#37]
Only the top ~100 px receives a touch event. If I have a button at y = 20px, it is clickable. If the button is at y = 150px, it is not clickable, UNTIL I scroll up so that button is within around the top 100px area.

Looks like the HPageView has a transparent area covering the header? I tried increasing zIndex of the header but it still doesn't work. I'll take a look at the source code if I get the time too, but maybe you know why this is happening?

**Comment by zyslife** [comment]
@Harin329  Thanks for your question. Can you use minimal code to make this problem appear?

**Comment by Harin329** [comment]
A really short & messy example below, but you'll notice the red touchable opacity won't "onPress" unless you're tapping in a very small area near the top left. 

`<TabView
        tabs={['a', 'b', 'c']}
        makeHeaderHeight={() => 200}
        renderScrollHeader={() => (
          <TouchableOpacity
            style={{ backgroundColor: 'red', width: 200, height: 200 }}
            onPress={() => {
              console.log('hi');
            }}
          />
        )}
        renderScene={(sceneProps) => {
          return (
            <HFlatList
              {...sceneProps}
              data={['1', '2', '3']}
              renderItem={(collection) => (
                <View>
                  <Text>{collection.item}</Text>
                </View>
              )}
              keyExtractor={(collection) => collection.index}
            />
          );
        }}
      />`

**Comment by Harin329** [comment]
My mistake sorry, found headerRespond is defaulted to false so that's why. My Mandarin is not good :/
