### ISSUE TITLE
如何给 整个tabview添加下拉控件?就像scrollview添加 refreshContrl那样

### ISSUE THREAD

**Issue by yuanteng666** [zyslife/react-native-head-tab-view#38]
如何给 整体tabview添加下拉控件?就像scrollview添加 refreshContrl那样，并且支持下拉回调

**Comment by zyslife** [comment]
现在整体tabview不能添加下拉控件和下拉回调，后续版本会增加这个功能。不过我近期较忙，需要等一段时间。

**Comment by yuanteng666** [comment]
> 现在整体tabview不能添加下拉控件和下拉回调，后续版本会增加这个功能。不过我近期较忙，需要等一段时间。

期待

**Comment by zyslife** [comment]
版本2.0.6添加了这个功能。
使用这两个属性onStartRefresh、isRefreshing
