### ISSUE TITLE
renderScrollHeader里面的点击事件无响应

### ISSUE THREAD

**Issue by GitXwj** [zyslife/react-native-head-tab-view#4]

**Comment by zyslife** [comment]
我刚发布了1.0.3版本，里面设置headerRespond={true} 可以解决 头部点击无响应的问题，但是滑动头部的时候不会触发整体组件上下滑动了。 （目前方案两者不可兼容）
@GitXwj

**Comment by GitXwj** [comment]
那renderScrollHeader里面的内容超过了屏幕的四分之三就无解了吗？

**Comment by zyslife** [comment]
> 那renderScrollHeader里面的内容超过了屏幕的四分之三就无解了吗？

我现在使用的方案确实没有好的解决办法，后面版本我有时间可能会解决该问题

**Comment by GitXwj** [comment]
希望大佬早点完善，建议把子页面的onScroll回调函数抛出来，方便使用者做一些自定义操作。
TabView:
 makeSceneParams(item, index) {
    const { makeHeaderHeight, faultHeight, renderScrollHeader, onPageScroll } = this.props;
    if (!renderScrollHeader) {
      return { item, index };
    }
    const { currentIndex, containerTrans, tabviewHeight, tabbarHeight } = this.state;

    const params = {
      item,
      index,
      isActive: currentIndex == index,
      containerTrans,
      makeHeaderHeight,
      faultHeight,
      onPageScroll
    };
    params.addListener = this.addListener;
    params.removeListener = this.removeListener;
    params.scenePageDidDrag = this.scenePageDidDrag;
    params.expectHeight = makeHeaderHeight() + tabviewHeight - tabbarHeight;

    return params;
  }
HPageViewHoc:
_onScroll(e) {
      const { onPageScroll } = this.props;
      onPageScroll(e);
      this.scrollTop = e.nativeEvent.contentOffset.y;
    }
