### ISSUE TITLE
有多个tab的时候，点击某一个tab，让这个tab在 scrollview 里面居中显示 有这个效果吗？

### ISSUE THREAD

**Issue by orzhtml** [zyslife/react-native-head-tab-view#41]

**Comment by orzhtml** [comment]
例如头条那个tabs
关注 推荐 图片 小视频 免费小说 …………

**Comment by zyslife** [comment]
> 例如头条那个tabs
> 
> 关注 推荐 图片 小视频 免费小说 …………

建议自己实现renderTabbar ，然后自定义Tabbar

**Comment by zyslife** [comment]
已经过去10天了，如果还有其他问题，请再次打开这个issues
