### ISSUE TITLE
新功能

### ISSUE THREAD

**Issue by yuanteng666** [zyslife/react-native-head-tab-view#42]
老哥，啥时候能添加头部和列表整体下拉功能？感觉现在的这种下拉不是很常用。

**Comment by zyslife** [comment]
> 老哥，啥时候能添加头部和列表整体下拉功能？感觉现在的这种下拉不是很常用。

嗯，我尽量这周添完成吧

**Comment by zyslife** [comment]
和[issues38](https://github.com/zyslife/react-native-head-tab-view/issues/38)是同一个问题， 已经在版本2.0.6添加
