### ISSUE TITLE
建议可以加上这个，不然吸顶的时候在状态栏会有内容展示

### ISSUE THREAD

**Issue by YSherlock** [zyslife/react-native-head-tab-view#44]
![image](https://user-images.githubusercontent.com/26606462/97653840-b3481c80-1a9c-11eb-951b-fc83f83f87e7.png)

TabView.tsx中加上这段代码
不然iphone 11 +的设备，状态栏会有head内容展示

**Comment by zyslife** [comment]
意见很好，我下个版本加上去

**Comment by zyslife** [comment]
@YSherlock 谢谢你的建议， 我考虑再三，觉得还是不要加上这部分代码，你可以在_renderScrollHeader实现自己头部组件时，加上这部分代码。因为可能其他人会需要沉浸式的状态栏。
