### ISSUE TITLE
头部无法滑动

### ISSUE THREAD

**Issue by McDreamy** [zyslife/react-native-head-tab-view#45]
我已经把headerRespond设置为true，可是当我往上滑头部一直在原地不会变小

**Comment by zyslife** [comment]
你好，有更详细的信息吗？
Example中的代码能够复现吗？
@McDreamy

**Comment by McDreamy** [comment]
我是参考ExampleNoPullRefresh的代码
这是我的代码，可是出来的结果头部无法滑动。而且FlatList是从中间开始，看不见我第一个Item
![Screen Recording 2020-11-02 at 2 51 18 PM](https://user-images.githubusercontent.com/9667496/97838734-c3216400-1d1b-11eb-951f-6243a0eeff08.gif)



`import React from 'react';
import {View, Text, FlatList} from 'react-native';
import {HPageViewHoc, TabView} from 'react-native-head-tab-view';

const data: number[] = [];
for (let i = 0; i < 100; i++) {
  data.push(i);
}
const HFlatList = HPageViewHoc(FlatList);
const HEAD_HEIGHT = 300;
const tabs = ['Tab 1', 'Tab 2'];
const App: () => React$Node = () => {
  const renderScrollHeader = () => {
    return (
      <View
        style={{
          height: 300,
          backgroundColor: 'yellow',
          justifyContent: 'center',
          alignItems: 'center',
        }}>
        <Text>Header Content</Text>
      </View>
    );
  };
  return (
    <View style={{flex: 1, backgroundColor: '#FFF'}}>
      <TabView
        tabs={tabs}
        renderScene={() => {
          return (
            <HFlatList
              data={data}
              renderItem={({item, index}) => (
                <View>
                  <Text>Item {index + 1}</Text>
                </View>
              )}
              keyExtractor={(item, index) => index.toString()}
            />
          );
        }}
        makeHeaderHeight={() => {
          return HEAD_HEIGHT;
        }}
        renderScrollHeader={renderScrollHeader}
        headerRespond={true}
      />
    </View>
  );
};

export default App;
`

**Comment by zyslife** [comment]
图片无法查看 @McDreamy

**Comment by McDreamy** [comment]
`
import React from 'react';
import {View, Text, FlatList} from 'react-native';
import {HPageViewHoc, TabView} from 'react-native-head-tab-view';

const data: number[] = [];
for (let i = 0; i < 100; i++) {
  data.push(i);
}
const HFlatList = HPageViewHoc(FlatList);
const HEAD_HEIGHT = 300;
const tabs = ['Tab 1', 'Tab 2'];
const App: () => React$Node = () => {
  const renderScrollHeader = () => {
    return (
      <View
        style={{
          height: HEAD_HEIGHT,
          backgroundColor: 'yellow',
          justifyContent: 'center',
          alignItems: 'center',
        }}>
        <Text>Header Content</Text>
      </View>
    );
  };
  return (
    <View style={{flex: 1, backgroundColor: '#FFF'}}>
      <TabView
        tabs={tabs}
        renderScene={() => {
          return (
            <HFlatList
              data={data}
              renderItem={({item, index}) => (
                <View>
                  <Text>Item {index + 1}</Text>
                </View>
              )}
              keyExtractor={(item, index) => index.toString()}
            />
          );
        }}
        makeHeaderHeight={() => {
          return HEAD_HEIGHT;
        }}
        renderScrollHeader={renderScrollHeader}
        headerRespond={true}
      />
    </View>
  );
};

export default App;
`

**Comment by zyslife** [comment]
//需要传入 sceneProps 到 HFlatList
renderScene={(sceneProps) => {
return (
<HFlatList
{...sceneProps}
data={data}
renderItem={({item, index}) => (
Item {index + 1}
)}
keyExtractor={(item, index) => index.toString()}
/>
);
}}
你应该这么写

**Comment by McDreamy** [comment]
可以了，非常感谢你！👍🏻
