### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mav10** [zyslife/react-native-head-tab-view#46]
Hello bro!

Thanks for providing such a cool component. I've already created something for my personal goals in my previous project but didn't share it. Now I wanted to find out something already written - to not copy and paste this from other my app and found your solution.

If you are not going to merge it into the `react-native-tab-view` project, so please think about good docs/readme in English.

**Comment by zyslife** [comment]
Thank you for your advice. I'll start working on it

**Comment by zyslife** [comment]
I have updated the document and I will continue to improve it in the future.
