### ISSUE TITLE
testID props are lost

### ISSUE THREAD

**Issue by mav10** [zyslife/react-native-head-tab-view#47]
Hi

I use FlatList wrapped into HPageViewHoc

and looks like `testID` props has been lost, can you take a look and provide it?

**Comment by zyslife** [comment]
> Hi
> 
> 
> 
> I use FlatList wrapped into HPageViewHoc
> 
> 
> 
> and looks like `testID` props has been lost, can you take a look and provide it?
> 
> 

I'm sorry, I didn't understand. can you give a simple example?

**Comment by mav10** [comment]
Yes sure

See I've got a TabView with product categories
Each scene is a Flatlist
```
const HFlatList = HPageViewHoc(FlatList);

<HFlatList
      {...props}
      data={props.products}
      renderItem={renderItem}
      keyExtractor={keyExtractor}
      ItemSeparatorComponent={ListItemSeparator}
      testID={'productMenu'}
      ListEmptyComponent={emptyControl}
    />
```

And **jest** can't see `testID` prop.
First of all, I tried to adjust `test id` naming - because I thought that in the case of `TabView` all scenes render at the same time and I can't find a specific element because it is not single.

I adjusted, but looks like inside of `HPageViewHoc` something is going wrong and I can't find in the hierarchy any child elements by testId or by accessibilityLabel.

I just got error like a 'instance with testId not found. Couldn't be a reason in the implementation of HOC?

**Comment by zyslife** [comment]
@mav10  Thank you for your detailed description. The reason testID hasn't been found is about 183 lines of the TabView file.
```
this.state.tabviewHeight > 0 ?
    <NativeViewGestureHandler ref={this.contentScroll} >
        {this._renderContent()}
    </NativeViewGestureHandler>
 : null
```
If you change `this.state.tabviewheight > 0` to `true`, you can fix this problem, however. This is obviously not a very good idea. I'm going to think about how do I optimize this part of the code.

**Comment by zyslife** [comment]
@mav10 I am sorry that I have been so busy these days that I have not dealt with your problem quickly.
I added a callback method tabsWillMount in V2.1.0, where XXX can be found after the method is called.
I don't know if it will solve your problem.

**Comment by mav10** [comment]
Ok, don't worry
I'm currently switching to another library to have stable tests.

I'll check later in a couple of sprints
Thanks for keeping in mind :)

**Comment by mav10** [comment]
@zyslife I've just checked and the state is the same.

I can't find any content inside the scene by jest

it failed by condition, which you described before.
it is inside `renderTabViewContent` method 
in this place. Looks like during tests tabViwHeigth does not change by native event and it is still 0.

```
this.state.tabviewHeight > 0 ?
                            <NativeViewGestureHandler ref={this.contentScroll} waitFor={this.drawer}>
                                {this._renderContent()}
                            </NativeViewGestureHandler>
                            : null
```

**Comment by mav10** [comment]
I suppose the problem in mocks of Animated component of react-native

I tried to mock it in my components but it failed because I use 'reanimated' lib and it has conflicts within it in jest enviroment

**Comment by mav10** [comment]
Looks like it can help
And we need to call it before each test, but sounds strange anyway
https://stackoverflow.com/questions/57961440/testing-onlayout-in-react-native

**Comment by mav10** [comment]
Does that check is really needed?
I'm talking about the height of tab view?

**Comment by zyslife** [comment]
> Does that check is really needed?
> I'm talking about the height of tab view?

I'm going to remove the judgment about height in a later version. Thank you for everything you've done for this.

**Comment by zyslife** [comment]
@mav10   I have removed the judgment about `this.state.tabviewHeight` in v2.1.4. If you have any other questions, I hope you can raise them. Thank you for your attention.

**Comment by zyslife** [comment]
After v3.0, the built-in tabs component is not supported.We will only extend the other tabs component so that each Tab page has a shared collapsible header.This issue will not occur again.
