### ISSUE TITLE
Option to bounce

### ISSUE THREAD

**Issue by plus-** [zyslife/react-native-head-tab-view#48]
First thank you for your work.

I noticed you [force the bounces property to false](https://github.com/zyslife/react-native-head-tab-view/blob/e9fecaf9c5187708de0eae329e6918963802e291/Example/react-native-head-tab-view/HPageViewHoc.tsx#L169)

Is there a reason in particular? Can we override this in any way?

Same question for `showsVerticalScrollIndicator`

**Comment by zyslife** [comment]
Thank you for your attention. If set showsVerticalScrollIndicator to true. There is a problem with ScrollIndicator displaying exceptions.I will fix this in a later version.

**Comment by plus-** [comment]
Not sure if this is the issue but maybe this can help: https://github.com/facebook/react-native/issues/26610#issuecomment-539843444

**Comment by zyslife** [comment]
> Not sure if this is the issue but maybe this can help: https://github.com/facebook/react-native/issues/26610#issuecomment-539843444

It's not this problem.

**Comment by zyslife** [comment]
@plus-  Hello, I have opened the attribute bounces and showsVerticalScrollIndicator. This change is in v2.0.8.

**Comment by plus-** [comment]
Thank you

**Comment by plus-** [comment]
I had a quick test, and it works fine on the first tab, but not the others.

scrollIndicator works fine on all tabs.

**Comment by plus-** [comment]
I've updated to v3 (and planning to update to v4 later down the road).

The bounce property  seems to have disappeared.
