### ISSUE TITLE
Detect when header is disappear

### ISSUE THREAD

**Issue by huurray** [zyslife/react-native-head-tab-view#49]
hello

i'd like to do something when header is disappeared because i scroll up.

so i tried to use onScroll function in HPageViewHoc(FlatList) to get scroll value. but it was duplicated.

is there way to detect the moment or get scroll value of HPageViewHoc(FlatList)?

please help me!!

**Comment by zyslife** [comment]
@huurray  In the current version. You can try the attribute `makeScrollTrans`, which makes it possible to get a scroll value of the current scenario via the callback method.For details, please refer to `ExampleFullFunctions.tsx`
In future releases, I will expose more animation values.
I wonder if I can help you.

**Comment by huurray** [comment]
it is very helpfull!! thanks!!
but in the future, i'd like to customize something with scrollY value!!
thanks for showing this library.
