### ISSUE TITLE
能导出类似ScrollView onRefresh的事件吗

### ISSUE THREAD

**Issue by godf4ther** [zyslife/react-native-head-tab-view#5]
能导出类似ScrollView onRefresh的事件吗

**Comment by zyslife** [comment]
> 能导出类似ScrollView onRefresh的事件吗

不知道你指的是哪一个 ScrollView？
我组件里面并没有用到ScrollView去封装，如果你说的是你标签页里面的ScrollView，那可以直接使用ScrollView的下拉刷新功能，不过由于这个组件会把ScrollView的contentContainerStyle的paddingTop设置为头部的高度，所以下拉刷新的菊花位置可能会异常，会显示在你预计的位置上方。
目前不推荐使用下拉刷新功能，如果有这个需求我后面完善下这部分功能
