### ISSUE TITLE
Option to lock horizontal sliding on first and last tabs

### ISSUE THREAD

**Issue by plus-** [zyslife/react-native-head-tab-view#50]
Right now you can slide left on the first tab and slide right on the last tab, it will do nothing but bounce horizontally.

It would be nice to have an option to lock the sliding on those directions of the respective tabs(the locked props on TabView will lock all directions)

**Comment by zyslife** [comment]
![bounce](https://user-images.githubusercontent.com/12319561/98553921-19be0d80-22db-11eb-99db-34db829a157c.png)
Don't you want the bounce effect?
If that's the case, I can add an option to the Tabview.

**Comment by plus-** [comment]
yes option for bounces false on the Tabview

**Comment by zyslife** [comment]
@plus- Ok, I will add this option tomorrow.

**Comment by zyslife** [comment]
@plus- I've added this option in v2.0.9

**Comment by plus-** [comment]
I've updated to v3 and notice the bounce option on the CollapsibleHeaderTabView (react-native-tab-view-collapsible-header) is no longer there. Any chance you could add it back?

**Comment by zyslife** [comment]
> I've updated to v3 and notice the bounce option on the CollapsibleHeaderTabView (react-native-tab-view-collapsible-header v0) is no longer there. Any chance you could add it back?

Well, first of all, on version v2, the property of `bounces ` was on my built-in TabView.

However, after the V3 release, the built-in TabView has been removed and you can only use other TAB components.

Ex: `react-native-scrollable-tab-view` 、  `react-native-tab-view`。
So you should look for that attribute in them.
> Right now you can slide left on the first tab and slide right on the last tab, it will do nothing but bounce horizontally.

In addition, the `react-native-tab-view` component does not have the above problem.

**Comment by zyslife** [comment]
> I've updated to v3 and notice the bounce option on the CollapsibleHeaderTabView (react-native-tab-view-collapsible-header v0) is no longer there. Any chance you could add it back?

Well, first of all, on version v2, the property of `bounces ` was on my built-in TabView.

However, after the V3 release, the built-in TabView has been removed and you can only use other TAB components.

Ex: `react-native-scrollable-tab-view` 、  `react-native-tab-view`。
So you should look for that attribute in them.
> Right now you can slide left on the first tab and slide right on the last tab, it will do nothing but bounce horizontally.

In addition, the `react-native-tab-view` component does not have the above problem.

**Comment by plus-** [comment]
Well I'm confused because I'm using your `CollapsibleHeaderTabView` from the `react-native-tab-view-collapsible-header` package (v0).

I get that it may be using the TabView from react-native-tab-view under the hood, but I don't have access to it do I?.

I also can confirm on v3 I have the horizontal bounce effect. I've tried setting bounce false on the CollapsibleHeaderTabView but it has no effect.

package.json:
```
"react-native-head-tab-view": "^3.0.4",
"react-native-pager-view": "^5.1.3",
"react-native-tab-view": "^3.0.1",
"react-native-tab-view-collapsible-header": "^0.0.1",

```

src:
```
return (
    <CollapsibleHeaderTabView
      makeHeaderHeight={makeHeaderHeight}
      renderScrollHeader={renderScrollHeader}
      navigationState={{ index, routes }}
      renderScene={renderScene}
      onIndexChange={setIndex}
      initialLayout={initialLayout}
      frozeTop={safeAreaInsets.top}
      renderTabBar={renderTabBar}
      style={tabViewStyle}
    />
```

**Comment by plus-** [comment]
by the way I notice the bounce is only on IOS

**Comment by zyslife** [comment]
> I get that it may be using the TabView from react-native-tab-view under the hood, but I don't have access to it do I?.

Yes,`react-native-tab-view` does not have the properties of bounce. Therefore, it also has no bounce effect in the horizontal direction.

Can you provide a simple demo, or a video that illustrates the problem? @plus-

**Comment by plus-** [comment]
This is my behaviour on IOS:

https://user-images.githubusercontent.com/841776/114986719-a37a9400-9e94-11eb-926b-0c4b713cb081.mov

**Comment by zyslife** [comment]
@plus-  I got it. With this library, the authors have changed the way they implement it. You can use the v2 version of `react-native-tab-view`

**Comment by plus-** [comment]
ok thank you

**Comment by plus-** [comment]
I've notice there is a [renderPager](https://github.com/satya164/react-native-tab-view/blob/350f783caad298d7c70f1b945bfeb3eb44b83ecd/example/src/CustomIndicatorExample.tsx#L166) property that you could expose[ in the same way you do for renderTabbar](https://github.com/zyslife/react-native-tab-view-collapsible-header/blob/main/createHeaderTabsComponent.tsx#L26)



This would I think let us overwrite the overscroll property of the pager.

**Comment by zyslife** [comment]
@plus-  
[I won't affect props for react-native-tab-view](https://github.com/zyslife/react-native-tab-view-collapsible-header/blob/c84a1c8bf6c1274c3372f98e37d1fd32cb6d7ef4/createHeaderTabsComponent.tsx#L44), so you can use the renderPager property.
