### ISSUE TITLE
function to switch tab programmatically

### ISSUE THREAD

**Issue by sagrawalcb** [zyslife/react-native-head-tab-view#51]
Is there a function to switch tab programmatically? Passing index or name as the parameter.

**Comment by zyslife** [comment]
You can try Tabview's goToPage.
```<Tabview ref={_ref=>this.tabview=_ref}/>```
```
switchTab=()=>{
    this.tabview.goToPage(1)
}
```
@sagrawalcb

**Comment by sagrawalcb** [comment]
Got it
