### ISSUE TITLE
stickySectionHeadersEnabled冲突

### ISSUE THREAD

**Issue by liubi520** [zyslife/react-native-head-tab-view#53]
当使用sectionList的时候，想让renderSectionHeader悬停，这个属性stickySectionHeadersEnabled为true的时候，头部滑动有问题，向上一下就到顶部了，然后安卓所有的renderScrollHeader都不能滑动，请问怎么破

**Comment by zyslife** [comment]
@liubi520  好的，我知道这个问题了，我看看怎么解决
在我解决之前如果你需要设置`stickySectionHeadersEnabled=true`, 你可以先尝试将 slideAnimated 设置为true，换成另一种滑动模式。(不过记得提供各个组件scrollToTop方法，参考`ExampleSlideAnimated.tsx`)

**Comment by zyslife** [comment]
> 当使用sectionList的时候，想让renderSectionHeader悬停，这个属性stickySectionHeadersEnabled为true的时候，头部滑动有问题，向上一下就到顶部了，然后安卓所有的renderScrollHeader都不能滑动，请问怎么破

我在v2.1.6解决了这个问题，`slideAnimated = true or false`都可以使用stickySectionHeadersEnabled了
