### ISSUE TITLE
Index is reset to 0 when have state update

### ISSUE THREAD

**Issue by JeanC17** [zyslife/react-native-head-tab-view#54]
Whenever there is a state update, the UI will re-render whole screen and tab bar index will reset to 0. 
Does anyone have solution to solve this?

**Comment by zyslife** [comment]
@JeanC17 Can you provide the minimum code to demonstrate the problem.

**Comment by virginiapujols** [comment]
I have the same issue. 
```
              <TabView
                tabs={data.menu.map((route) => route.title)}
                onChangeTab={(tab) => { 
                  console.log('TabView.onChangeTab', tab);
                  this.setState({index: tab.curIndex});
                }}
                renderScene={ (route) => {
                  return (
                    <MenuListScreen
                      ref={(menu) => this._menu = menu }
                      navigation={this.props.navigation}
                      indexSelected={route.index}
                    />
                  );
                }}
              />

```

I need to have the `index` value in my `state`. The `TabView` component works fine as long as I don't call `this.setState({/*whatever in here/*});`.  When I add the `setState` it keeps going back to the first tab.

**Comment by zyslife** [comment]
> I have the same issue.
> 
> ```
>               <TabView
>                 tabs={data.menu.map((route) => route.title)}
>                 onChangeTab={(tab) => { 
>                   console.log('TabView.onChangeTab', tab);
>                   this.setState({index: tab.curIndex});
>                 }}
>                 renderScene={ (route) => {
>                   return (
>                     <MenuListScreen
>                       ref={(menu) => this._menu = menu }
>                       navigation={this.props.navigation}
>                       indexSelected={route.index}
>                     />
>                   );
>                 }}
>               />
> ```
> 
> I need to have the `index` value in my `state`. The `TabView` component works fine as long as I don't call `this.setState({/*whatever in here/*});`. When I add the `setState` it keeps going back to the first tab.

You can try to fix the `tabs`. That should solve the problem.
Example:
```
this.state = {
       tabs: ['tab1', 'tab2', 'tab3'],
}

<TabView
       tabs={this.state.tabs}
/>
```

In addition, I will update this version soon, and you will be able to use the other tabs components. Such as `react-native-tab-view`

**Comment by zyslife** [comment]
After **v3.0**, the built-in tabs component is not supported.We will only extend the **other tabs component** so that each Tab page has a shared collapsible header.  

**The following components are currently supported:**  
[react-native-scrollable-tab-view](https://github.com/ptomasroos/react-native-scrollable-tab-view)  
[react-native-tab-view](https://github.com/satya164/react-native-tab-view)   

For detailed usage, please refer to [Example](https://github.com/zyslife/react-native-head-tab-view#Example) and [Installation](https://github.com/zyslife/react-native-head-tab-view#Installation).
