### ISSUE TITLE
头部包含ScrollView时，滑动冲突

### ISSUE THREAD

**Issue by tuyazuo** [zyslife/react-native-head-tab-view#55]
在页面的头部放置了一个横向的ScrollView组件，在安卓上左右滑动时，经常会无法滑动
![image](https://user-images.githubusercontent.com/5566986/104088353-39ed5700-52a1-11eb-8bcb-c8a472f25058.png)

**Comment by zyslife** [comment]
> 在页面的头部放置了一个横向的ScrollView组件，在安卓上左右滑动时，经常会无法滑动
> 
> ![image](https://user-images.githubusercontent.com/5566986/104088353-39ed5700-52a1-11eb-8bcb-c8a472f25058.png)
> 
> 

能提供更详细的信息么？或者给个代码示例

**Comment by tuyazuo** [comment]
以下是个测试用例，头部含有ScrollView组件，当头部的内容滚动到头或尾的时候，再往回滚动，在安卓上经常出现拖不动的情况。
```javascript
import React from 'react'
import {View, Text, Image, ScrollView, TouchableOpacity} from 'react-native'
import {TabView, Tabbar} from 'react-native-head-tab-view'

export default class testHeader extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      label: ['1', '2', '3'],
      recdList: [0, 1, 2, 3, 4],
    }
  }

  _renderScene = (sceneProps: { item: string, index: number }) => {
    const {index} = sceneProps
    return <View {...sceneProps} id={index}/>
  }

  _renderTabBar = (tabbarProps) => (
    <Tabbar {...tabbarProps} scrollEnabled={true} tabs={this.state.label} lineStyle={{backgroundColor: '#0F141A'}}
    />
  )

  _header = () => (
    <View style={{width: '100%', height: 290, backgroundColor: '#daf'}}>
      <Text style={{height: 88}}>今日推荐</Text>
      <ScrollView
        showsHorizontalScrollIndicator={false}
        style={{width: '100%', height: 175, backgroundColor: '#ba4'}}
        horizontal={true}
        contentContainerStyle={{paddingLeft: 24, paddingRight: 8, paddingTop: 12}}
      >
        {this.state.recdList.map((item, index)=>(
          <TouchableOpacity activeOpacity={0.8} style={{width: 112, height: 158, marginRight: 25}} key={index}>
            <View>
              <Image style={{width: 112, height: 158}} source={{uri: 'https://img.php.cn/upload/avatar/000/000/164/59190898474f6485.png'}}/>
            </View>
          </TouchableOpacity>))}
      </ScrollView>
    </View>
  )

  render() {
    return (
      <View style={{flex: 1, backgroundColor: '#fff'}}>
        <TabView
          averageTab={false}
          tabs={this.state.label}
          renderTabBar={this._renderTabBar}
          renderScene={this._renderScene}
          renderScrollHeader={this._header}
          makeHeaderHeight={() => {
            return 290
          }}
          frozeTop={33}
          onChangeTab={this.onChangeTab.bind(this)}
        />
      </View>
    )
  }

  onChangeTab(event) {

  }
}
```

**Comment by zyslife** [comment]
> 以下是个测试用例，头部含有ScrollView组件，当头部的内容滚动到头或尾的时候，再往回滚动，在安卓上经常出现拖不动的情况。
> 
> ```js
> import React from 'react'
> import {View, Text, Image, ScrollView, TouchableOpacity} from 'react-native'
> import {TabView, Tabbar} from 'react-native-head-tab-view'
> 
> export default class testHeader extends React.Component {
>   constructor(props) {
>     super(props)
>     this.state = {
>       label: ['1', '2', '3'],
>       recdList: [0, 1, 2, 3, 4],
>     }
>   }
> 
>   _renderScene = (sceneProps: { item: string, index: number }) => {
>     const {index} = sceneProps
>     return <View {...sceneProps} id={index}/>
>   }
> 
>   _renderTabBar = (tabbarProps) => (
>     <Tabbar {...tabbarProps} scrollEnabled={true} tabs={this.state.label} lineStyle={{backgroundColor: '#0F141A'}}
>     />
>   )
> 
>   _header = () => (
>     <View style={{width: '100%', height: 290, backgroundColor: '#daf'}}>
>       <Text style={{height: 88}}>今日推荐</Text>
>       <ScrollView
>         showsHorizontalScrollIndicator={false}
>         style={{width: '100%', height: 175, backgroundColor: '#ba4'}}
>         horizontal={true}
>         contentContainerStyle={{paddingLeft: 24, paddingRight: 8, paddingTop: 12}}
>       >
>         {this.state.recdList.map((item, index)=>(
>           <TouchableOpacity activeOpacity={0.8} style={{width: 112, height: 158, marginRight: 25}} key={index}>
>             <View>
>               <Image style={{width: 112, height: 158}} source={{uri: 'https://img.php.cn/upload/avatar/000/000/164/59190898474f6485.png'}}/>
>             </View>
>           </TouchableOpacity>))}
>       </ScrollView>
>     </View>
>   )
> 
>   render() {
>     return (
>       <View style={{flex: 1, backgroundColor: '#fff'}}>
>         <TabView
>           averageTab={false}
>           tabs={this.state.label}
>           renderTabBar={this._renderTabBar}
>           renderScene={this._renderScene}
>           renderScrollHeader={this._header}
>           makeHeaderHeight={() => {
>             return 290
>           }}
>           frozeTop={33}
>           onChangeTab={this.onChangeTab.bind(this)}
>         />
>       </View>
>     )
>   }
> 
>   onChangeTab(event) {
> 
>   }
> }
> ```

你好，版本2.1.7解决了

**Comment by 345ml** [comment]
How to fix this problem?
