### ISSUE TITLE
头部太高，不能滑动

### ISSUE THREAD

**Issue by madongd** [zyslife/react-native-head-tab-view#57]
如果renderScrollHeader这个太高的话，不能滑动

**Comment by zyslife** [comment]
你好，能提供一个简单的代码示例吗？

**Comment by madongd** [comment]
我查了一下原因，原来是在android情况下触摸组件react-native-gesture-handler，没有生效，在MainActivity里添加`import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;`
然后再添加
 @Override
       protected ReactActivityDelegate createReactActivityDelegate() {
         return new ReactActivityDelegate(this, getMainComponentName()) {
           @Override
           protected ReactRootView createRootView() {
            return new RNGestureHandlerEnabledRootView(MainActivity.this);
           }
         };
       }
这样触摸组件就能用了

**Comment by yaoz0816** [comment]
你好，我的android上面手势也失效。我用的react-native-navigation路由里面加如上代码报错？
