### ISSUE TITLE
安卓头部不能滑动，IOS可以。

### ISSUE THREAD

**Issue by yoursaaron** [zyslife/react-native-head-tab-view#59]
把库拿到项目下面使用，安卓头部不能滑动，IOS可以。

**Comment by zyslife** [comment]
#57 可以看看这个.
或者[https://docs.swmansion.com/react-native-gesture-handler/docs/#installation](react-native-gesture-handler的文档)或许能帮到你.

**Comment by yoursaaron** [comment]
经过测试，安卓系统放到tab导航下面，头部不能滑动。其他导航可以。请问该如何解决？
@react-navigation/stack                              可以
@react-navigation/bottom-tabs                 不行
@react-navigation/drawer                           可以

**Comment by zyslife** [comment]
> 经过测试，安卓系统放到tab导航下面，头部不能滑动。其他导航可以。请问该如何解决？
> @react-navigation/stack 可以
> @react-navigation/bottom-tabs 不行
> @react-navigation/drawer 可以

你解决了吗
