### ISSUE TITLE
如果header层是个轮播图 或者时刻在切换  应该怎么办

### ISSUE THREAD

**Issue by ngxu** [zyslife/react-native-head-tab-view#6]

**Comment by ngxu** [comment]
除了切换tab轮播图会有异常外  也不能滑动轮播图  滑动轮播图会切换tab  轮播图也不能点击了

**Comment by ngxu** [comment]
> 除了切换tab轮播图会有异常外也不能滑动轮播图滑动轮播图会切换tab轮播图也不能点击了
这里给TabView添加headerRespond={true}可以解决滑动点击问题  
不知道切换tab怎么防止轮播图出现问题 
![IMG_2496](https://user-images.githubusercontent.com/43433064/80275583-da501b00-8714-11ea-85ea-47265f0575bb.GIF)

**Comment by zyslife** [comment]
> > 除了切换tab轮播图会有异常外也不能滑动轮播图滑动轮播图会切换tab轮播图也不能点击了
> > 这里给TabView添加headerRespond={true}可以解决滑动点击问题
> > 不知道切换tab怎么防止轮播图出现问题
> > ![IMG_2496](https://user-images.githubusercontent.com/43433064/80275583-da501b00-8714-11ea-85ea-47265f0575bb.GIF)

@ngxu 你好，请问切换tab 具体是有什么问题？我没看出来

**Comment by ngxu** [comment]
@zyslife 比如轮播图正在过度动画中  切换tab  轮播图就没有过度动画了  或者切换tab后 轮播图直接换了一张 问题不大

**Comment by zyslife** [comment]
> @zyslife 比如轮播图正在过度动画中 切换tab 轮播图就没有过度动画了 或者切换tab后 轮播图直接换了一张 问题不大

@ngxu   你可以尝试将轮播图封装到一个组件中，然后使用PureComponent，应该是可以解决该问题

**Comment by ngxu** [comment]
@zyslife 谢谢  这个功能挺好的 RN缺少这种功能  看了源码  挺厉害的  我有点搞不明白 我以前也用过动画来驱动头部跟着滑动  可以做到不会抖动  获取scrollView的滑动坐标传递给header做动画处理  但是有个传递过程  有0.几秒的延迟   你是怎么解决这个延迟的  求回答

**Comment by ngxu** [comment]
@zyslife  谢谢啦  我在轮播图中使用了shouldComponentUpdate解决了header为轮播图问题  PureComponent好像判断不了  
给轮播图添加一个props  通过shouldComponentUpdate 判定props来防止切换tab造成轮播图render()

**Comment by zyslife** [comment]
好的，那我关掉这个问题了哦~
