### ISSUE TITLE
也没有下拉刷新功能的属性

### ISSUE THREAD

**Issue by 1591161042** [zyslife/react-native-head-tab-view#61]

**Comment by zyslife** [comment]
如果你设置了onStartRefresh 以及isRefreshing 就会有这功能

**Comment by zyslife** [comment]
如果你设置了onStartRefresh 以及isRefreshing 就会有这功能

**Comment by zyslife** [comment]
如果你设置了onStartRefresh 以及isRefreshing 就会有这功能

**Comment by zyslife** [comment]
如果你设置了onStartRefresh 以及isRefreshing 就会有这功能
