### ISSUE TITLE
TabView的lineStyle好像没有办法设置啊

### ISSUE THREAD

**Issue by lifudea** [zyslife/react-native-head-tab-view#62]
现在只能通过这里面来修改lineStyle的样式吗

<img width="348" alt="截屏2021-02-01上午11 57 36" src="https://user-images.githubusercontent.com/50136663/106413289-af091200-6484-11eb-92fa-986b14a52957.png">

**Comment by lifudea** [comment]
现在只能通过修改tabBar.tsx里面的styles = StyleSheet.create({lineStyle: {}})来修改lineStyle的样式吗

**Comment by zyslife** [comment]
是可以通过lineStyle进行修改的，比如这样写
```
    _renderTabBar = (tabbarProps: TabbarInfo<string>) => {
        return <Tabbar
            {...tabbarProps}
            lineStyle={{backgroundColor:'red'}}
        />
    }

    render() {
        return (
            <View style={{ flex: 1, backgroundColor: '#FFF' }}>         
                <TabView
                    tabs={this.state.tabs}
                    renderScene={this._renderScene}
                    makeHeaderHeight={this.makeHeaderHeight}
                    renderScrollHeader={this._renderScrollHeader}
                    renderTabBar={this._renderTabBar}
                />
            </View>
        )
    }
```

**Comment by lifudea** [comment]
好的谢谢了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zyslife"<notifications@github.com&gt;; 
发送时间: 2021年2月1日(星期一) 下午2:12
收件人: "zyslife/react-native-head-tab-view"<react-native-head-tab-view@noreply.github.com&gt;; 
抄送: "咿呀咿呀咿"<525537973@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zyslife/react-native-head-tab-view] TabView的lineStyle好像没有办法设置啊 (#62)





 
是可以通过lineStyle进行修改的，比如这样写
     _renderTabBar = (tabbarProps: TabbarInfo<string&gt;) =&gt; {         return <Tabbar             {...tabbarProps}             lineStyle={{backgroundColor:'red'}}         /&gt;     }     render() {         return (             <View style={{ flex: 1, backgroundColor: '#FFF' }}&gt;                          <TabView                     tabs={this.state.tabs}                     renderScene={this._renderScene}                     makeHeaderHeight={this.makeHeaderHeight}                     renderScrollHeader={this._renderScrollHeader}                     renderTabBar={this._renderTabBar}                 /&gt;             </View&gt;         )     }
