### ISSUE TITLE
怎么实现类似这样的交互

### ISSUE THREAD

**Issue by chen513755770** [zyslife/react-native-head-tab-view#63]
![normal-video](https://user-images.githubusercontent.com/34224261/106583284-e3adc400-657f-11eb-9b35-ad8629cd044a.gif)

**Comment by chen513755770** [comment]
我通过设置scrollEnabled 和内联滑动去做但是 不是很流畅

**Comment by zyslife** [comment]
你这是一张静态图吧，我看不出来你具体要实现的效果.
另外版本更新3.0了，可以使用其他第三方的tabs组件了

**Comment by chen513755770** [comment]
> 你这是一张静态图吧，我看不出来你具体要实现的效果.
> 另外版本更新3.0了，可以使用其他第三方的tabs组件了

![1](https://user-images.githubusercontent.com/34224261/108579357-76f93e80-7361-11eb-8ae6-0eefe590e455.gif)

第一样图gif没有设置重复播放。。。

**Comment by zyslife** [comment]
> > 你这是一张静态图吧，我看不出来你具体要实现的效果.
> 
> > 另外版本更新3.0了，可以使用其他第三方的tabs组件了
> 
> 
> 
> ![1](https://user-images.githubusercontent.com/34224261/108579357-76f93e80-7361-11eb-8ae6-0eefe590e455.gif)
> 
> 
> 
> 第一张图gif没有设置重复播放。。。

这个交互好像没有用到标签页吧，看起来只需要监听列表组件onscroll，然后绝对定位的头部做个动画就可以了

**Comment by chen513755770** [comment]
> > > 你这是一张静态图吧，我看不出来你具体要实现的效果。
> > 
> > 
> > > 另外版本更新3.0了，可以使用其他第三方的tabs组件了
> > 
> > 
> > ![1个](https://user-images.githubusercontent.com/34224261/108579357-76f93e80-7361-11eb-8ae6-0eefe590e455.gif)
> > 第一张图gif没有设置重复播放。。。
> 
> 这个相互作用好像没有用到标签页吧，看起来只需要监听列表组件onscroll，然后绝对定位的头部做个动画就可以了

我的其中一个标签页 想实现这个交互

**Comment by zyslife** [comment]
@chen513755770 不知道你是否实现你想要的效果，但是看起来这个issues应该关闭了，如果还有其他问题，欢迎打开新issues
