### ISSUE TITLE
下拉刷新问题

### ISSUE THREAD

**Issue by shenxingchao** [zyslife/react-native-head-tab-view#64]
您好，目前学习rn中用到您的组件
怎么为下拉刷新展示一个图标
或者怎么使用renderRefreshControl
目前这样展示不能达到目标

````javascript
isRefreshing={isRefreshing}

onStartRefresh={() => {
  // console.log('开始刷新')
  setIsRefreshing(true)
  setShowActivityIndicator(true)
  setTimeout(() => {
    // console.log('刷新结束')
    setIsRefreshing(false)
    setShowActivityIndicator(false)
  }, 1500)
}}

{showActivityIndicator && (
    <View
      style={{
        position: 'relative',
        justifyContent: 'center'
      }}
    >
      <ActivityIndicator
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          right: 0
        }}
        size="large"
        color={ThemeColor.primary}
      />
    </View>
  )}
````
想要实现自定义的下拉刷新图标，类似于案例中的这个，能跟随屏幕滚动的
![](https://github.com/zyslife/react-native-head-tab-view/raw/master/demoGIF/demo_ios.gif)

看到文档写的renderRefreshControl 是渲染一个自定义下拉刷新控件，我用了RN的下拉刷新控件，没有效果
```javascript
isRefreshing={isRefreshing}

renderRefreshControl={() => (
  <RefreshControl
    refreshing={isRefreshing}
    onRefresh={() => {
      setIsRefreshing(true)
      console.log('开始刷新')
      setTimeout(() => {
        console.log('刷新结束')
        setIsRefreshing(false)
      }, 2000)
    }}
  />
)}
```

**Comment by shenxingchao** [comment]
如下图
![](https://raw.githubusercontent.com/shenxingchao/react-native-job/master/demo.gif)

**Comment by zyslife** [comment]
目前版本不支持自定义下拉刷新控件，renderRefreshControl字段是无效的。 下个版本我会修复这个问题.

**Comment by shenxingchao** [comment]
> 目前版本不支持自定义下拉刷新控件，renderRefreshControl字段是无效的。 下个版本我会修复这个问题.

好的，谢谢

**Comment by will002** [comment]
> 目前版本不支持自定义下拉刷新控件，renderRefreshControl字段是无效的。 下个版本我会修复这个问题.

请问一下修复的思路可以说一下吗～～现在有需求急需自定义下拉刷新

**Comment by zyslife** [comment]
> > 目前版本不支持自定义下拉刷新控件，renderRefreshControl字段是无效的。 下个版本我会修复这个问题.
> 
> 请问一下修复的思路可以说一下吗～～现在有需求急需自定义下拉刷新

版本已经升到了3.0.1，修复了renderRefreshControl字段，目前使用上有什么问题可以反馈给我，我会判断是在
v4版还是v3版处理

**Comment by will002** [comment]
> > > 目前版本不支持自定义下拉刷新控件，renderRefreshControl字段是无效的。 下个版本我会修复这个问题.
> > 
> > 
> > 请问一下修复的思路可以说一下吗～～现在有需求急需自定义下拉刷新
> 
> 版本已经升到了3.0.1，修复了renderRefreshControl字段，目前使用上有什么问题可以反馈给我，我会判断是在
> v4版还是v3版处理

请教一下，我们封装了一个native的下拉刷新组件，正常只要下拉刷新组件嵌套FlatList，就可以实现下拉刷新。这个组件放到目前的库，不生效，请教如何支持呢～～～

**Comment by zyslife** [comment]
> > > > 目前版本不支持自定义下拉刷新控件，renderRefreshControl字段是无效的。 下个版本我会修复这个问题.
> 
> > > 
> 
> > > 
> 
> > > 请问一下修复的思路可以说一下吗～～现在有需求急需自定义下拉刷新
> 
> > 
> 
> > 版本已经升到了3.0.1，修复了renderRefreshControl字段，目前使用上有什么问题可以反馈给我，我会判断是在
> 
> > v4版还是v3版处理
> 
> 
> 
> 请教一下，我们封装了一个native的下拉刷新组件，正常只要下拉刷新组件嵌套FlatList，就可以实现下拉刷新。这个组件放到目前的库，不生效，请教如何支持呢～～～

你是要自定义标签页的下拉刷新还是整个tabview的下拉刷新组件？

**Comment by will002** [comment]
> > > > > 目前版本不支持自定义下拉刷新控件，renderRefreshControl字段是无效的。 下个版本我会修复这个问题.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 请问一下修复的思路可以说一下吗～～现在有需求急需自定义下拉刷新
> > 
> > 
> > > 
> > 
> > 
> > > 版本已经升到了3.0.1，修复了renderRefreshControl字段，目前使用上有什么问题可以反馈给我，我会判断是在
> > 
> > 
> > > v4版还是v3版处理
> > 
> > 
> > 请教一下，我们封装了一个native的下拉刷新组件，正常只要下拉刷新组件嵌套FlatList，就可以实现下拉刷新。这个组件放到目前的库，不生效，请教如何支持呢～～～
> 
> 你是要自定义标签页的下拉刷新还是整个tabview的下拉刷新组件？

自定义标签页的，tab下有3个FlatList，每个FlatList想加上下拉刷新～～

**Comment by will002** [comment]
> > > > > > 目前版本不支持自定义下拉刷新控件，renderRefreshControl字段是无效的。 下个版本我会修复这个问题.
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > 请问一下修复的思路可以说一下吗～～现在有需求急需自定义下拉刷新
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 版本已经升到了3.0.1，修复了renderRefreshControl字段，目前使用上有什么问题可以反馈给我，我会判断是在
> > > 
> > > 
> > > > v4版还是v3版处理
> > > 
> > > 
> > > 请教一下，我们封装了一个native的下拉刷新组件，正常只要下拉刷新组件嵌套FlatList，就可以实现下拉刷新。这个组件放到目前的库，不生效，请教如何支持呢～～～
> > 
> > 
> > 你是要自定义标签页的下拉刷新还是整个tabview的下拉刷新组件？
> 
> 自定义标签页的，tab下有3个FlatList，每个FlatList想加上下拉刷新～～类似美团外卖订单列表的下拉刷新

**Comment by zyslife** [comment]
> > > > > > 目前版本不支持自定义下拉刷新控件，renderRefreshControl字段是无效的。 下个版本我会修复这个问题.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 请问一下修复的思路可以说一下吗～～现在有需求急需自定义下拉刷新
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 版本已经升到了3.0.1，修复了renderRefreshControl字段，目前使用上有什么问题可以反馈给我，我会判断是在
> 
> > > 
> 
> > > 
> 
> > > > v4版还是v3版处理
> 
> > > 
> 
> > > 
> 
> > > 请教一下，我们封装了一个native的下拉刷新组件，正常只要下拉刷新组件嵌套FlatList，就可以实现下拉刷新。这个组件放到目前的库，不生效，请教如何支持呢～～～
> 
> > 
> 
> > 你是要自定义标签页的下拉刷新还是整个tabview的下拉刷新组件？
> 
> 
> 
> 自定义标签页的，tab下有3个FlatList，每个FlatList想加上下拉刷新～～

好的，我今天晚点更新个版本，你再试试

**Comment by zyslife** [comment]
@will002  能看看你在Flatlist上自定义的native下拉刷新组件的用法吗？

**Comment by will002** [comment]
> > > > > > > 目前版本不支持自定义下拉刷新控件，renderRefreshControl字段是无效的。 下个版本我会修复这个问题.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 请问一下修复的思路可以说一下吗～～现在有需求急需自定义下拉刷新
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 版本已经升到了3.0.1，修复了renderRefreshControl字段，目前使用上有什么问题可以反馈给我，我会判断是在
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > v4版还是v3版处理
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 请教一下，我们封装了一个native的下拉刷新组件，正常只要下拉刷新组件嵌套FlatList，就可以实现下拉刷新。这个组件放到目前的库，不生效，请教如何支持呢～～～
> > 
> > 
> > > 
> > 
> > 
> > > 你是要自定义标签页的下拉刷新还是整个tabview的下拉刷新组件？
> > 
> > 
> > 自定义标签页的，tab下有3个FlatList，每个FlatList想加上下拉刷新～～
> 
> 好的，我今天晚点更新个版本，你再试试



> @will002 能看看你在Flatlist上自定义的native下拉刷新组件的用法吗？


> @will002 能看看你在Flatlist上自定义的native下拉刷新组件的用法吗？

export default class PullToRefreshView extends React.Component<Props> {
  static defaultProps = {
    pullToRefreshEnabled: true,
    refreshing: false
  }

  private pullToRefreshView = null
  private platform: PlatformOSType

  constructor(props: Props) {
    super(props)
    this.platform = Platform.OS
  }

  componentWillReceiveProps(nextProps: Props) {
    if (
      this.platform === 'android' &&
      this.props.refreshing === true &&
      nextProps.refreshing === false
    ) {
      this.stopRefreshing()
    }
  }

  render() {
    const { style, onRefresh, refreshing, enabled } = this.props
      return (
        <NativePullToRefreshView
          style={style}
          pullDownEnabled={enabled}
          onPullDown={onRefresh}
          loading={refreshing}
        >
          {this.props.children}
        </NativePullToRefreshView>
      )
  }

  stopRefreshing = () => {
    NativeModules.UIManager.dispatchViewManagerCommand(
      findNodeHandle(this.pullToRefreshView),
      NativeModules.UIManager.getViewManagerConfig('PullRefresh').Commands
        .refreshComplete,
      []
    )
  }
}

interface NativePullToRefreshViewPropsIOS extends ViewProps {
  pullDownEnabled?: boolean
  onPullDown?: () => void | null
  pullUpEnabled?: boolean
  onPullUp?: () => void | null
  loading?: boolean
}

enum HeaderType {
  Common,
  MainPager
}

interface NativePullToRefreshViewPropsAndroid extends ViewProps {
  onRefresh: () => void | null
  headerType: HeaderType
  pullDownEnabled?: boolean
}

const NativePullToRefreshView = getNativePullToRefreshView()

function getNativePullToRefreshView(): React.ComponentClass<
  NativePullToRefreshViewPropsIOS | NativePullToRefreshViewPropsAndroid
> {
    return requireNativeComponent(
      'PullToRefreshView'
    )
}

**Comment by will002** [comment]
> > > > > > > > 目前版本不支持自定义下拉刷新控件，renderRefreshControl字段是无效的。 下个版本我会修复这个问题.
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > > 请问一下修复的思路可以说一下吗～～现在有需求急需自定义下拉刷新
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > 版本已经升到了3.0.1，修复了renderRefreshControl字段，目前使用上有什么问题可以反馈给我，我会判断是在
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > v4版还是v3版处理
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > 请教一下，我们封装了一个native的下拉刷新组件，正常只要下拉刷新组件嵌套FlatList，就可以实现下拉刷新。这个组件放到目前的库，不生效，请教如何支持呢～～～
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 你是要自定义标签页的下拉刷新还是整个tabview的下拉刷新组件？
> > > 
> > > 
> > > 自定义标签页的，tab下有3个FlatList，每个FlatList想加上下拉刷新～～
> > 
> > 
> > 好的，我今天晚点更新个版本，你再试试
> 
> > @will002 能看看你在Flatlist上自定义的native下拉刷新组件的用法吗？
> 
> > @will002 能看看你在Flatlist上自定义的native下拉刷新组件的用法吗？
> 
> export default class PullToRefreshView extends React.Component {
> static defaultProps = {
> pullToRefreshEnabled: true,
> refreshing: false
> }
> 
> private pullToRefreshView = null
> private platform: PlatformOSType
> 
> constructor(props: Props) {
> super(props)
> this.platform = Platform.OS
> }
> 
> componentWillReceiveProps(nextProps: Props) {
> if (
> this.platform === 'android' &&
> this.props.refreshing === true &&
> nextProps.refreshing === false
> ) {
> this.stopRefreshing()
> }
> }
> 
> render() {
> const { style, onRefresh, refreshing, enabled } = this.props
> return (
> 
> {this.props.children}
> 
> )
> }
> 
> stopRefreshing = () => {
> NativeModules.UIManager.dispatchViewManagerCommand(
> findNodeHandle(this.pullToRefreshView),
> NativeModules.UIManager.getViewManagerConfig('PullRefresh').Commands
> .refreshComplete,
> []
> )
> }
> }
> 
> interface NativePullToRefreshViewPropsIOS extends ViewProps {
> pullDownEnabled?: boolean
> onPullDown?: () => void | null
> pullUpEnabled?: boolean
> onPullUp?: () => void | null
> loading?: boolean
> }
> 
> enum HeaderType {
> Common,
> MainPager
> }
> 
> interface NativePullToRefreshViewPropsAndroid extends ViewProps {
> onRefresh: () => void | null
> headerType: HeaderType
> pullDownEnabled?: boolean
> }
> 
> const NativePullToRefreshView = getNativePullToRefreshView()
> 
> function getNativePullToRefreshView(): React.ComponentClass<
> NativePullToRefreshViewPropsIOS | NativePullToRefreshViewPropsAndroid
> 
> > {
> > return requireNativeComponent(
> > 'PullToRefreshView'
> > )
> > }

this.props.chidren 就是FlatList

**Comment by zyslife** [comment]
@will002   如果是这样的用法，那应该还需要改你的native下拉刷新组件才可以了。

**Comment by will002** [comment]
> @will002 如果是这样的用法，那应该还需要改你的native下拉刷新组件才可以了。

只要可以支持，native组件也可以改，应该怎么改呢，我这一点思路都没有～～

**Comment by zyslife** [comment]
> > @will002 如果是这样的用法，那应该还需要改你的native下拉刷新组件才可以了。
> 
> 只要可以支持，native组件也可以改，应该怎么改呢，我这一点思路都没有～～

方便的话你可以把你的native下拉刷新组件上传到一个github地址上，我有时间看看

**Comment by will002** [comment]
> > > @will002 如果是这样的用法，那应该还需要改你的native下拉刷新组件才可以了。
> > 
> > 
> > 只要可以支持，native组件也可以改，应该怎么改呢，我这一点思路都没有～～
> 
> 方便的话你可以把你的native下拉刷新组件上传到一个github地址上，我有时间看看

好的

**Comment by will002** [comment]
> > > @will002 如果是这样的用法，那应该还需要改你的native下拉刷新组件才可以了。
> > 
> > 
> > 只要可以支持，native组件也可以改，应该怎么改呢，我这一点思路都没有～～
> 
> 方便的话你可以把你的native下拉刷新组件上传到一个github地址上，我有时间看看


> > > > @will002 如果是这样的用法，那应该还需要改你的native下拉刷新组件才可以了。
> > > 
> > > 
> > > 只要可以支持，native组件也可以改，应该怎么改呢，我这一点思路都没有～～
> > 
> > 
> > 方便的话你可以把你的native下拉刷新组件上传到一个github地址上，我有时间看看
> 
> 好的

方便加一下联系方式吗,不知道你的技术栈～～wechat:    willwang_peng

**Comment by shenxingchao** [comment]
已解决
