### ISSUE TITLE
FlatList 里面的数据 TouchableOpacity 点击无反应

### ISSUE THREAD

**Issue by orzhtml** [zyslife/react-native-head-tab-view#65]
FlatList 里面的数据 TouchableOpacity 点击无反应，这是怎么回事，另外 Example 里面图片也无法显示

**Comment by orzhtml** [comment]
测试下来，只有安卓手机有这个问题，ios能正常点击

**Comment by orzhtml** [comment]
测试下来，只有安卓手机有这个问题，ios能正常点击

**Comment by zyslife** [comment]
@orzhtml 是否使用过Example?Example中是否会有同样的问题？ 单独使用tab-view组件会有这个问题吗

**Comment by orzhtml** [comment]
> @orzhtml 是否使用过Example?Example中是否会有同样的问题？ 单独使用tab-view组件会有这个问题吗

是的，用过Example也是一样的，例子里面底部不是有个回到顶部吗，这个按钮也无响应。这个问题只有安卓存在。

**Comment by zyslife** [comment]
@orzhtml  那这个问题比较奇怪了，如果只使用FlatList，TouchableOpacity可以点击吗？rn使用的是debug还是release模式运行的呢？

**Comment by orzhtml** [comment]
> @orzhtml 那这个问题比较奇怪了，如果只使用FlatList，TouchableOpacity可以点击吗？rn使用的是debug还是release模式运行的呢？

单独使用 FlatList ，都是没问题的，视乎只有 react-native-head-tab-view, react-native-tab-view-collapsible-header 用了后才不行，RN的debug也是正常能用的

**Comment by orzhtml** [comment]
补充下，TouchableOpacity 的 activeOpacity 是有效果的，但是 onPress 里无响应，console.log 或者 做别的操作 都无响应。

**Comment by orzhtml** [comment]
- React:16.13.1
- React Native:0.63.2
- React-Native-Gesture-Handler:1.7.0

**Comment by zyslife** [comment]
> - React:16.13.1
> 
> - React Native:0.63.2
> 
> - React-Native-Gesture-Handler:1.7.0

那能否试试用到你的项目中，看看是否也是同样的效果

**Comment by orzhtml** [comment]
> > * React:16.13.1
> > * React Native:0.63.2
> > * React-Native-Gesture-Handler:1.7.0
> 
> 那能否试试用到你的项目中，看看是否也是同样的效果

试过了，先在自己的项目中发现的，然后用例子运行后也是一样

**Comment by zyslife** [comment]
尝试去掉手势，将改为 GestureContainer.tsx文件中的render方法改为下面这样.排查下问题.
```
    render() {
        return (
            <Animated.View style={styles.container}>
                <Animated.View style={{ ...styles.container, transform: this.getTransform() }}>
                    {this._renderTabViewContainer()}
                </Animated.View>
                {this._renderRefreshControl()}
            </Animated.View>
        )
    }
```

@orzhtml

**Comment by TuNguyenThanh** [comment]
same issue +1

**Comment by zyslife** [comment]
> same issue +1  

Thank you for your question. Could you help me troubleshoot this problem?
Try changing the GestureContainer file's render function to the code below.

```
    render() {
        return (
            <Animated.View style={styles.container}>
                <Animated.View style={{ ...styles.container, transform: this.getTransform() }}>
                    {this._renderTabViewContainer()}
                </Animated.View>
                {this._renderRefreshControl()}
            </Animated.View>
        )
    }
```

Let's see if we can solve this problem.

**Comment by orzhtml** [comment]
> 尝试去掉手势，将改为 GestureContainer.tsx文件中的render方法改为下面这样.排查下问题.
> 
> ```
>     render() {
>         return (
>             <Animated.View style={styles.container}>
>                 <Animated.View style={{ ...styles.container, transform: this.getTransform() }}>
>                     {this._renderTabViewContainer()}
>                 </Animated.View>
>                 {this._renderRefreshControl()}
>             </Animated.View>
>         )
>     }
> ```
> 
> @orzhtml

这个有效，安卓可以点击，只是没了pull 手势了

**Comment by zyslife** [comment]
[Make sure it's not this bug](https://github.com/software-mansion/react-native-gesture-handler/issues/1338)

Please try to fix the version of `react-native-gesture-handler` in v.1.9.0.  
@orzhtml @TuNguyenThanh

**Comment by zyslife** [comment]
> > [Make sure it's not this bug](https://github.com/software-mansion/react-native-gesture-handler/issues/1338)
> > Please try to fix the version of `react-native-gesture-handler` in v.1.9.0.
> 
> 安装的："react-native-gesture-handler": "^1.10.3"
> 安卓下点击还是无效

可以加下我qq: 274237321 ，沟通下其他细节

**Comment by zyslife** [comment]
[related bug](https://github.com/software-mansion/react-native-gesture-handler/issues/594).

**Comment by zyslife** [comment]
已解决 v3.0.3
