### ISSUE TITLE
监听List(我用的FlatList)的 onScroll，会导致原本的头部上滑失效

### ISSUE THREAD

**Issue by SeriousSnow** [zyslife/react-native-head-tab-view#66]
由于要监听滑动事件，改变某些元素的透明度，
添加后onScroll事件后，原来的事件失效，初步判定是因为
NormalSceneContainer.tsx文件
const { isRefreshing, ContainerView, forwardedRef, index, ...rest } = this.props

                            <SceneListComponent
                                ContainerView={ContainerView}
                                zForwardedRef={this.setAndForwardRef}
                                headerHeight={this.getPaddingTop()}
                                expectHeight={expectHeight}
                                onScroll={this.getOnScroll()}
                                onScrollBeginDrag={this._onScrollBeginDrag}
                                onContentSizeChange={this._onContentSizeChange}
                                {...rest}
                            />

这里rest对象里面的onScroll 会覆盖掉上面的onScroll={this.getOnScroll()}

**Comment by zyslife** [comment]
> 由于要监听滑动事件，改变某些元素的透明度，
> 添加后onScroll事件后，原来的事件失效，初步判定是因为
> NormalSceneContainer.tsx文件
> const { isRefreshing, ContainerView, forwardedRef, index, ...rest } = this.props
> 
> ```
>                         <SceneListComponent
>                             ContainerView={ContainerView}
>                             zForwardedRef={this.setAndForwardRef}
>                             headerHeight={this.getPaddingTop()}
>                             expectHeight={expectHeight}
>                             onScroll={this.getOnScroll()}
>                             onScrollBeginDrag={this._onScrollBeginDrag}
>                             onContentSizeChange={this._onContentSizeChange}
>                             {...rest}
>                         />
> ```
> 
> 这里rest对象里面的onScroll 会覆盖掉上面的onScroll={this.getOnScroll()}

可以尝试函数`makeScrollTrans`.  具体用法可以参照 `ExampleScrollTrans.tsx`

**Comment by SeriousSnow** [comment]
谢谢，非常好用，也怪我没有看完Example
