### ISSUE TITLE
CollapsibleHeaderTabView在android下不能下拉刷新，ios可以正常

### ISSUE THREAD

**Issue by firstmyname002** [zyslife/react-native-head-tab-view#68]
CollapsibleHeaderTabView
设置了onStartRefresh，isRefreshing。
在ios下正常下拉刷新，但是android不行

**Comment by zyslife** [comment]
看看是这个问题吗？ #57 #59

**Comment by firstmyname002** [comment]
> 看看是这个问题吗？ #57 #59

#57解决了这个问题

**Comment by firstmyname002** [comment]
> > 看看是这个问题吗？ #57 #59
> 
> #57解决了这个问题

很抱歉再麻烦下。虽然可以下拉刷新，但是TouchableOpacity的onPress事件不响应了

**Comment by zyslife** [comment]
> > > 看看是这个问题吗？ #57 #59
> 
> > 
> 
> > #57解决了这个问题
> 
> 
> 
> 很抱歉再麻烦下。虽然可以下拉刷新，但是TouchableOpacity的onPress事件不响应了

请问你版本号多少？升到最新了看看

**Comment by firstmyname002** [comment]
> > > > 看看是这个问题吗？ #57 #59
> > 
> > 
> > > 
> > 
> > 
> > > #57解决了这个问题
> > 
> > 
> > 很抱歉再麻烦下。虽然可以下拉刷新，但是TouchableOpacity的onPress事件不响应了
> 
> 请问你版本号多少？升到最新了看看

react-native: 0.59.10
react-native-tab-view-collapsible-header: 0.0.3
react-native-head-tab-view: 3.0.4

是这个版本

**Comment by zyslife** [comment]
@firstmyname002  尝试按这个issue去排除下问题，然后随时联系我. #65
