### ISSUE TITLE
安卓端下拉刷新问题

### ISSUE THREAD

**Issue by kimiciwi** [zyslife/react-native-head-tab-view#69]
设置了onStartRefresh与isRefreshing，但是无法触发onStartRefresh。有没有好的solution呀？关于react-native-gesture-handler的设置的话是需要重新build吗？我的框架基于ignite的。

**Comment by firstmyname002** [comment]
你查看上一条

**Comment by zyslife** [comment]
@kimiciwi 你好，问题解决了吗？ 应该是react-native-gesture-handler这个库没生效吧。可以查看 #57 #68 .
如果还有问题可以再次打开这个issues.
