### ISSUE TITLE
探讨下如何修复下刷新控件位置，或者自定义下拉刷新控件

### ISSUE THREAD

**Issue by ngxu** [zyslife/react-native-head-tab-view#7]
我试了以下方案
1、onScroll去监听 不用自带的刷新功能  使用自定义  ios能监听到负值  也就是到顶部了还可以继续下拉可以做到自定义刷新  但是Android不可以  最多到顶部就不能下拉了  只能监听到0    结论  ios可以  安卓不行

 2、 添加手势监听滑动距离，使用rn自带手势:结论 不行手势功能只能监听到几个值就会被scrollview的滑动所替换;
使用第三方手势控件，可以做到监听任何时候的滑动坐标以及距离，但是tab左右切换受到影响，不能左右滑动了，如果能解决左右滑动的问题，估计能实现。

3、因为rn自带的刷新控件，不支持修改样式，没有暴露原生的全部方法，这里Android的刷新控件有一个方法是修改距离顶部的高度的，所以考虑封装原生自定义控件。  不过不懂原生， 搞了一半实在是不懂了

**Comment by ngxu** [comment]
Rn的RefreshControl刷新控件是用的原生SwiperrefreshLayout，这个SwiperrefreshLayout有个方法叫setProgressViewEndTarget的，可以修改刷新控件距离顶部的高度，但是rn没有暴露这个方法[捂脸]，不懂原生不知道怎么添加这个方法给rn用

**Comment by zyslife** [comment]
嗯，是这样的
1、下拉刷新 
2、头部点击和上下滑动不能共存
这两个问题确实是这个组件的缺陷，但是我目前太忙也没时间去重写这个组件。只能闲下来了去完善。

**Comment by zyslife** [comment]
1、下拉刷新
2、头部点击和上下滑动不能共存 （此功能已经添加）

**Comment by frankyLHJ** [comment]
Android使用原生的SmartRefreshLayout库，ios用了MJRefresh，自定义了下拉刷新，但是不知道怎么用HPageViewHoc包裹能够让头部滑动。这个图的场景就是搜索框平移缩小到顶部。


![B4919707-041A-4F48-8EE7-A03BC294B3D8](https://user-images.githubusercontent.com/17977044/89180693-dd389280-d5c4-11ea-9cac-91b3ffef4247.png)
![Screenshot_1596455894](https://user-images.githubusercontent.com/17977044/89180710-e6296400-d5c4-11ea-95a9-90f051558a02.png)
@zyslife 能请教一下吗？

**Comment by zyslife** [comment]
你的意思是下拉刷新的时候，让搜索栏移动位置吗？你现在下拉刷新做到什么程度了，整体视图会跟随手指下拉吗？


发自我的iPhone

**Comment by frankyLHJ** [comment]
@zyslife 是上滑的时候搜索栏往上平移宽度变小不会盖住右边的小按钮，有点像京东APP首页的搜索栏。目前下拉刷新视图是随手指下拉的。

**Comment by zyslife** [comment]
_makeScrollTrans，那你可以看看Example2里面这个方法，看看能否通过这个动画控制

发自我的iPhone

**Comment by frankyLHJ** [comment]
> _makeScrollTrans，那你可以看看Example2里面这个方法，看看能否通过这个动画控制 发自我的iPhone
> […](#)
> 在 2020年8月4日，09:57，frankyLHJ ***@***.***> 写道： ﻿ @zyslife 是上滑的时候搜索栏往上平移宽度变小不会盖住右边的小按钮，有点像京东APP首页的搜索栏。目前下拉刷新视图是随手指下拉的。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯嗯，我之前用_makeScrollTrans普通的Flatlist是可以实现，但是跟现在的自定义下拉刷新组件一起用上滑时，头部不能滑动了。
