### ISSUE TITLE
Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?

### ISSUE THREAD

**Issue by 1591161042** [zyslife/react-native-head-tab-view#70]

**Comment by zyslife** [comment]
[babel.config.js](https://github.com/zyslife/react-native-head-tab-view/blob/master/Example/babel.config.js)

```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
};
```

I have already added it, are you the latest code.
@1591161042

**Comment by 1591161042** [comment]
这里面是加了的，还是不行

**Comment by 1591161042** [comment]
"@react-native-community/viewpager": "^3.3.0",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.0.0",
    "react-native-scrollable-tab-view": "^1.0.0",
    "react-native-tab-view": "^2.15.2"

**Comment by zyslife** [comment]
尝试清除缓存
```sh
npm start -- --reset-cache
or
yarn start --reset-cache
```

@1591161042

**Comment by 1591161042** [comment]
安卓遇到过这种问题吗，Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.

**Comment by 1591161042** [comment]
我尝试运行你demo中的demo，也是一样的问题
![Uploading WeChate7bc59ed931548bdbdc4d64c7247c466.png…]()

**Comment by 1591161042** [comment]
我尝试运行你demo中的安卓项目，也是一样的问题

**Comment by zyslife** [comment]
> 安卓遇到过这种问题吗，Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.

[react-native-reanimated/issues/1825](https://github.com/software-mansion/react-native-reanimated/issues/1825)
Try to find solutions in issues of `react-native-reanimated`.

**Comment by 1591161042** [comment]
这里一定要用react-native-reanimated2.0.0吗，安卓还是不行，iOS可以的

**Comment by zyslife** [comment]
> 这里一定要用react-native-reanimated2.0.0吗，安卓还是不行，iOS可以的

react-native-reanimated版本大于等于2.0.0就可以了.

**Comment by shenxingchao** [comment]
我按照[react-native-reanimated install](https://docs.swmansion.com/react-native-reanimated/docs/installation/) 升级了一遍，也不行 安卓  
报错  TypeError: Object is not a function, js engine: hermes
升级前package.json
```json
{
    "react-native-head-tab-view": "^3.0.2",
    "react-native-reanimated": "^1.13.2",
    "react-native-scrollable-tab-view-collapsible-header": "^0.0.5",
}
```
升级后
```json
{
    "react-native-head-tab-view": "^4.0.0-rc.0",
    "react-native-reanimated": "^2.0.0",
    "react-native-scrollable-tab-view-collapsible-header": "^1.0.0-rc3",
}
```

**Comment by zyslife** [comment]
> 一遍

是在你自己的项目中对吗？麻烦提供下rn的版本号

**Comment by zyslife** [comment]
> 我按照[react-native-reanimated install](https://docs.swmansion.com/react-native-reanimated/docs/installation/) 升级了一遍，也不行 安卓
> 报错 TypeError: Object is not a function, js engine: hermes
> 升级前package.json
> 
> ```json
> {
>     "react-native-head-tab-view": "^3.0.2",
>     "react-native-reanimated": "^1.13.2",
>     "react-native-scrollable-tab-view-collapsible-header": "^0.0.5",
> }
> ```
> 
> 升级后
> 
> ```json
> {
>     "react-native-head-tab-view": "^4.0.0-rc.0",
>     "react-native-reanimated": "^2.0.0",
>     "react-native-scrollable-tab-view-collapsible-header": "^1.0.0-rc3",
> }
> ```

是在你自己的项目中对吗？麻烦提供下rn的版本号

**Comment by shenxingchao** [comment]
> > 我按照[react-native-reanimated install](https://docs.swmansion.com/react-native-reanimated/docs/installation/) 升级了一遍，也不行 安卓
> > 报错 TypeError: Object is not a function, js engine: hermes
> > 升级前package.json
> > ```json
> > {
> >     "react-native-head-tab-view": "^3.0.2",
> >     "react-native-reanimated": "^1.13.2",
> >     "react-native-scrollable-tab-view-collapsible-header": "^0.0.5",
> > }
> > ```
> > 
> > 
> > 升级后
> > ```json
> > {
> >     "react-native-head-tab-view": "^4.0.0-rc.0",
> >     "react-native-reanimated": "^2.0.0",
> >     "react-native-scrollable-tab-view-collapsible-header": "^1.0.0-rc3",
> > }
> > ```
> 
> 是在你自己的项目中对吗？麻烦提供下rn的版本号

    "react-native": "0.63.4",

**Comment by zyslife** [comment]
@shenxingchao 
1. 首先确保安装[react-native-reanimated文档](https://docs.swmansion.com/react-native-reanimated/docs/installation)仔细的正确安装。
2. 
```sh
cd android && ./gradlew clean
```
3.
```sh
npm start -- --reset-cache
or
yarn start --reset-cache
```
应该是没有问题的

**Comment by shenxingchao** [comment]
@zyslife 录了个视频麻烦看下[Link](http://demo.o8o8o8.com/gif/error.gif)

**Comment by zyslife** [comment]
> @zyslife 按着步骤来的，升级了rn版本，还是不行，录了个视频麻烦看下[Link](http://demo.o8o8o8.com/gif/error.gif)
我有几点建议
1、我怀疑可能是其他第三方库造成的错误
2、react-navigation的可能性比较高，可以尝试将其升级到v6
3、可以创建一个新rn项目尝试下

**Comment by 1591161042** [comment]
v3中这个makeScrollTrans属性，现在如何监听滚动事件

**Comment by 1591161042** [comment]
之前需要这个改变页面的导航的显示，现在如何处理这里呢
_makeScrollTrans = (scrollValue: Animated.Value) => {
    this.setState({ scrollValue })
 }

**Comment by zyslife** [comment]
> 之前需要这个改变页面的导航的显示，现在如何处理这里呢
> _makeScrollTrans = (scrollValue: Animated.Value) => {
> this.setState({ scrollValue })
> }

现在用法一样
```
    const makeScrollTrans = (scrollTrans: Animated.SharedValue<number>) => {
        setScrollTrans(scrollTrans)
    }
```
只不过scrollTrans的类型变了，需要使用react-native-reanimated去操作动画

**Comment by 1591161042** [comment]
有例子吗，如何写

**Comment by 1591161042** [comment]
下面是我的代码片段
_makeScrollTrans = (scrollTrans: Animated.SharedValue<number>) => {
    this.setState({ scrollTrans })
}

const Props = {
      renderScrollHeader: this._renderScrollHeader,
      modeType: this.getModeType(),
      makeScrollTrans: this._makeScrollTrans,
   }
 const { scrollValue } = this.state;
<Animated.View style={{
            justifyContent: 'space-between', alignItems: 'flex-end',flexDirection:'row',
            opacity: scrollValue.interpolate({
                inputRange: [0, HEAD_HEIGHT - FROZE_TOP],
                outputRange: [0, 1],
            }),
            width:G_WIN_WIDTH,
            height:FROZE_TOP,
            backgroundColor:'#ffffff',
            position: 'absolute',
            top:0,
            left:0
        }}>

            <View style={{width:px2dp(100)}}/>
            <Text style={{height:px2dp(44),lineHeight:px2dp(44),color: '#1B1B1B', fontSize: 18}}>Sdeer</Text>
            {this.navRightLayout()}
          </Animated.View>

**Comment by 1591161042** [comment]
求指教，就是滚动的时候顶部的导航栏会出现，不太会用react-native-reanimated

**Comment by shenxingchao** [comment]
@zyslife 我的可以了，是用FScrollView的时候忘记改了，还是老的用法。
我尝试了一下,其他发现的问题有
tab下拉刷新执行了3次
```ts
 onStartRefresh={() => {
  console.log('开始刷新')
    setIsRefreshing(true)
    setTimeout(() => {
      console.log('刷新结束')
      setIsRefreshing(false)
    }, 1500)
  }}
```
```log
 LOG  开始刷新
 LOG  开始刷新
 LOG  开始刷新
 LOG  刷新结束
 LOG  刷新结束
 LOG  刷新结束
```
手指滑动切换tab，拖动会触发当前tab内容下的<TouchableHighlight> onPress事件
还有就是点击tab标签切换内容，不会马上切换，会等下一个内容加载完才切换，这个问题是不是react-native-scrollable-tab-view的问题

**Comment by zyslife** [comment]
> @zyslife 我的可以了，是用FScrollView的时候忘记改了，还是老的用法。
> 我尝试了一下,其他发现的问题有
> tab下拉刷新执行了3次
> 
> ```ts
>  onStartRefresh={() => {
>   console.log('开始刷新')
>     setIsRefreshing(true)
>     setTimeout(() => {
>       console.log('刷新结束')
>       setIsRefreshing(false)
>     }, 1500)
>   }}
> ```
> 
> ```
>  LOG  开始刷新
>  LOG  开始刷新
>  LOG  开始刷新
>  LOG  刷新结束
>  LOG  刷新结束
>  LOG  刷新结束
> ```
> 
> 手指滑动切换tab，拖动会触发当前tab内容下的 onPress事件
> 还有就是点击tab标签切换内容，不会马上切换，会等下一个内容加载完才切换，这个问题是不是react-native-scrollable-tab-view的问题

-  下拉刷新多次调用的问题已经解决，晚点提交
-  第2个3的问题，暂时还没复现，请问你用Example能复现出来吗？

**Comment by zyslife** [comment]
问题已经过去很久了，我先关闭了，如果还存在疑问可以再次打开或者重新提issue.
