### ISSUE TITLE
Warning: Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by surethink** [zyslife/react-native-head-tab-view#73]
## Describe the bug
更新了最新版本，报了如下错误

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in SceneView (created by Pager)
    in RNCViewPager (at PagerView.tsx:143)
    in PagerView (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (created by Pager)
    in Pager (created by TabView)
    in RCTView (at View.js:34)
    in View (created by TabView)
    in TabView (at createHeaderTabsComponent.tsx:33)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:441)
    in AnimatedComponent(View) (at createAnimatedComponent.js:452)
    in ForwardRef(AnimatedComponentWrapper) (at GestureContainer.tsx:531)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:441)
    in AnimatedComponent(View) (at createAnimatedComponent.js:452)
    in ForwardRef(AnimatedComponentWrapper) (at GestureContainer.tsx:530)
    in PanGestureHandler (at GestureContainer.tsx:521)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:441)
    in AnimatedComponent(View) (at createAnimatedComponent.js:452)
    in ForwardRef(AnimatedComponentWrapper) (at GestureContainer.tsx:545)
    in TapGestureHandler (at GestureContainer.tsx:541)
    in ForwardRef(GestureContainer) (at createHeaderTabsComponent.tsx:39)
    in CollapsibleHeaderTabView (at createHeaderTabsComponent.tsx:12)
    in ForwardRef (at Index.js:305)
    in RNCSafeAreaView (at Index.js:304)
### Expected behavior
 不要报错
## Package versions  
  "react-native": "0.63.4",
    "react-native-head-tab-view": "^4.0.0-rc.2",
    "react-native-tab-view": "^3.0.0",
    "react-native-reanimated": "^2.0.1",
    "react-native-tab-view-collapsible-header": "^2.0.0",

- React:
- React Native:
- React-Native-Gesture-Handler

**Comment by zyslife** [comment]
@surethink 你好，你是运行的Example吗？ 是否有定时器或者异步任务在页面退出的时候没有关闭呢?

**Comment by surethink** [comment]
> @surethink 你好，你是运行的Example吗？ 是否有定时器或者异步任务在页面退出的时候没有关闭呢?

抱歉，应该是我的问题
