### ISSUE TITLE
react-native-reanimated动画库貌似会和React Native Debugger冲突

### ISSUE THREAD

**Issue by edwards19900128** [zyslife/react-native-head-tab-view#75]
## Describe the bug
貌似不开Debug,跑起来还是没问题,一开Debugger就报下面的错误了
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.
跑去react-native-reanimated的issuse里面翻了翻，貌似作者回答是不太会支持
![image](https://user-images.githubusercontent.com/11594850/112868176-56ee3500-90ee-11eb-8c06-9d1f2d30bcf6.png)
有没大佬遇到同样的问题...
BTW, Flipper是真的难用...Axios请求监听&DVA等状态库支持...

## Package versions  

- React:16.13.1
- React Native:0.63.4
- React-Native-Gesture-Handler:1.10.3

**Comment by zyslife** [comment]
以后会支持的，这是一个趋势，只不过react-native-reanimated提前使用了未公开的TurboModule

**Comment by edwards19900128** [comment]
> 以后会支持的，这是一个趋势，只不过react-native-reanimated提前使用了未公开的TurboModule
OK....那就先暂时用Flipper & console.log打法调试了~~坐等配套更新了...
