### ISSUE TITLE
onStartRefresh函数问题

### ISSUE THREAD

**Issue by surethink** [zyslife/react-native-head-tab-view#76]
render组件示例：
            <CollapsibleHeaderTabView   onStartRefresh={onStartRefresh} />
奇怪，我的组件示例无法显示，编辑状态有，发布后就没了。反正就是CollapsibleHeaderTabView 组件上的onStartRefresh函数问题
//函数示例
    const onStartRefresh = () => {
        console.log(targetMessage,93111)
        setIsRefreshing(true)
        setTimeout(() => {
            if (targetMessage.functionInTopic == 1) {
              do something
            } else {
                do other thing
            }
            setIsRefreshing(false)
        }, 10);
    }

问题1：
    onStartRefresh函数依赖于target message，不过target message初始为null，后面拿到数据赋值后，再onStartRefresh查到的target message仍然为null。期望能根据target message的实际值来做判断。我用useCallback把函数包起来貌似也无效
不知道是我写法问题，还是组件问题，特求教，谢谢！
ps:印象中老版本没有这个问题

问题2:
    新版本感觉顺滑了很多，很赞。不过似乎tab里的内容渲染速度比上个版本慢了不少，之前head部分和tab内容几乎一起渲染，更新版本后，tab里的内容要等一会儿才渲染出来。这个情况供参考

**Comment by zyslife** [comment]
@surethink 你好，
问题1：
我自己尝试过复现，但是是能随时取到引用的外部变量最新数据的。 希望你能提供一个能够复现的最简单代码。
问题2：
确实是会有这个问题，因为这个版本会等到header的初始化高度测量完成，才会将tab内容的透明度调为1。所以如果你能提供一个初始头部高度，赋值在headerHeight上，就不会有这个问题了

**Comment by surethink** [comment]
> headerHeight



> @surethink 你好，
> 问题1：
> 我自己尝试过复现，但是是能随时取到引用的外部变量最新数据的。 希望你能提供一个能够复现的最简单代码。

页面逻辑有点复杂，我搞搞看吧

> 问题2：
> 确实是会有这个问题，因为这个版本会等到header的初始化高度测量完成，才会将tab内容的透明度调为1。所以如果你能提供一个初始头部高度，赋值在headerHeight上，就不会有这个问题了

headerHeight初始值之前我赋了的，比较小（12，改大了也一样）。是不是在我渲染head时，又将tab内容的透明度调为0了？
ps.我的场景是像微博详情一样，head部分是个高度不确定的消息，希望能考虑下类似场景的优化，谢谢

**Comment by zyslife** [comment]
@surethink 如果headerHeight有值，透明度会一直是1，所以应该会直接显示出来，这两个问题最好都把逻辑尽量简化，抽出一个demo，可以一起分析看看

**Comment by surethink** [comment]
> @surethink 如果headerHeight有值，透明度会一直是1，所以应该会直接显示出来，这两个问题最好都把逻辑尽量简化，抽出一个demo，可以一起分析看看

已发你163邮箱

**Comment by zyslife** [comment]
> > @surethink 如果headerHeight有值，透明度会一直是1，所以应该会直接显示出来，这两个问题最好都把逻辑尽量简化，抽出一个demo，可以一起分析看看
> 
> 已发你163邮箱

我已经看到你的示例代码。
问题1:是我这边的问题，我会尽快修复
问题2:看起来是因为你那边的延时导致
```
setTimeout(() => {
            setTargetMessage({ id: 19928 })
            setChildrenMessagesRelated([{ id: 393 }, { id: 2929 }])
        }, 1000);
```

**Comment by zyslife** [comment]
v4.0.0-rc.3
