### ISSUE TITLE
设置了frozeTop，HFlatList内可以往上滚动frozeTop高度

### ISSUE THREAD

**Issue by 276259822** [zyslife/react-native-head-tab-view#77]
#### [ExampleScrollTrans](https://github.com/zyslife/react-native-head-tab-view/blob/master/Example/src/ExampleScrollTrans.tsx#L148)中设置了frozeTop，在内容不足一屏情况下，HFlatList内可以往上滚动相对应的高度
![image](https://user-images.githubusercontent.com/15446036/113100186-a71fe100-922d-11eb-8548-9f45f5774556.png)

### Expected behavior
希望不要往上滚动，是否可以通过修改[expectHeight](https://github.com/zyslife/react-native-head-tab-view/blob/v4.0.0-rc.2/Example/react-native-head-tab-view/GestureContainer.tsx#L511)解决
```expectHeight: headerHeight + Math.floor(tabviewHeight) - frozeTop,```

## Package versions  

- React: "16.11.0"
- React Native: "^0.63.3"
- React-Native-Gesture-Handler: "^1.5.0"
- react-native-reanimated: "^2.0.1"

**Comment by zyslife** [comment]
@276259822  是可以通过expectHeight解决，我会尽快修复。

**Comment by zyslife** [comment]
v4.0.0-rc.3

**Comment by 276259822** [comment]
谢谢
