### ISSUE TITLE
安卓在滚动的时候如滚动动画未停止再进行手势滑动操作会重置滚动原始位置

### ISSUE THREAD

**Issue by raymenchow** [zyslife/react-native-head-tab-view#81]
## Describe the bug

phone:'SM-G8870 - 9'

## Package versions  

react: 16.11.0 => 16.11.0 
react-native: ^0.63.3 => 0.63.4
react-native-gesture-handler: "^1.5.0",

已经更新到rc.4

**Comment by zyslife** [comment]
@raymenchow 你好，能更新详细的描述问题吗？ 我没太明白.

**Comment by raymenchow** [comment]
https://user-images.githubusercontent.com/49781609/113952198-16677900-97ca-11eb-92de-5a8e9bdbee16.mp4

**Comment by zyslife** [comment]
>  1617841702223228.mp4

你好，可以提供能够复现的示例代码吗？

**Comment by zyslife** [comment]
@raymenchow  你好，问题是否已经解决？
