### ISSUE TITLE
ios真机调试，HFlatList用到的异步数据有机率无法看到

### ISSUE THREAD

**Issue by 276259822** [zyslife/react-native-head-tab-view#82]
## Describe the bug
iphone11，版本14.4.1
当`headerHeight` + `tabbarHeight` 大于屏幕高度，HFlatList异步获取数据，有机率触发数据已渲染，但`renderItem`内容看不到的情况，该item内容位置可以点击跳转到其他页面，从其他页面返回又可以正常看到。如果HFlatList固定高度则不会出现，修改ContainerView的[minHeight](https://github.com/zyslife/react-native-head-tab-view/blob/master/Example/react-native-head-tab-view/createCollapsibleScrollView.tsx#L337)暂时已解决问题
`contentContainerStyle={{ paddingTop: headerHeight, minHeight: expectHeight + 1 }}`
### Expected behavior
正常显示HFlatList内容
## Package versions  

- React: "16.11.0"
- React Native: "^0.63.3"
- React-Native-Gesture-Handler: "^1.5.0"
- react-native-reanimated: "^2.0.1"

**Comment by zyslife** [comment]
@276259822 谢谢，我想我应该知道是什么原因了，可能实际的HFlatList高度比 expectHeight的高度小不到1个像素，导致透明度没有设置成1。 下个版本我会修复。

**Comment by zyslife** [comment]
@276259822 已经在rc. 4版本修复

**Comment by SeriousSnow** [comment]
我的RN版本是是0.57,只能用3.0版本的，请问3.0版本的会修复这个bug吗

**Comment by SeriousSnow** [comment]
@zyslife

**Comment by zyslife** [comment]
> 我的RN版本是是0.57,只能用3.0版本的，请问3.0版本的会修复这个bug吗

好的，我今天晚点修复

**Comment by SeriousSnow** [comment]
> > 我的RN版本是是0.57,只能用3.0版本的，请问3.0版本的会修复这个bug吗
> 
> 好的，我今天晚点修复

好的，非常感谢

**Comment by SeriousSnow** [comment]
> > 我的RN版本是是0.57,只能用3.0版本的，请问3.0版本的会修复这个bug吗
> 
> 好的，我今天晚点修复

我的那个主要是运行在安卓上，有三个FlatList，第二个和第三个看不到渲染的Item，可以点击，这个bug只有有很少一部分手机有，不知道是不是与题主痛一个bug，麻烦开发者了

**Comment by SeriousSnow** [comment]
> > 我的RN版本是是0.57,只能用3.0版本的，请问3.0版本的会修复这个bug吗
> 
> 好的，我今天晚点修复

理论上应该是同一个bug，我试了一下按照题主的方法 NormalSceneContainer.tsx 改为 minHeight: expectHeight + 1 就可以显示

**Comment by zyslife** [comment]
> > > 我的RN版本是是0.57,只能用3.0版本的，请问3.0版本的会修复这个bug吗
> > 
> > 
> > 好的，我今天晚点修复
> 
> 理论上应该是同一个bug，我试了一下按照题主的方法 NormalSceneContainer.tsx 改为 minHeight: expectHeight + 1 就可以显示

可以在NormalSceneContainer的fitSceneHeight函数下 加上打印吗？
```
console.log('fitSceneHeight===>>>', contentHeight, expectHeight);
```
我这边没有复现这个问题，希望你能协助我排查下问题

**Comment by SeriousSnow** [comment]
这是两个页面的打印


&nbsp;



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月8日(星期四) 下午5:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zyslife/react-native-head-tab-view] ios真机调试，HFlatList用到的异步数据有机率无法看到 (#82)





    
我的RN版本是是0.57,只能用3.0版本的，请问3.0版本的会修复这个bug吗
  
好的，我今天晚点修复
  
理论上应该是同一个bug，我试了一下按照题主的方法 NormalSceneContainer.tsx 改为 minHeight: expectHeight + 1 就可以显示
  
可以在NormalSceneContainer的fitSceneHeight函数下 加上打印吗？
 console.log('fitSceneHeight===&gt;&gt;&gt;', contentHeight, expectHeight);  
我这边没有复现这个问题，希望你能协助我排查下问题
 
&mdash;

**Comment by zyslife** [comment]
@SeriousSnow 是不是发送的内容有问题， 我这边看不到

**Comment by SeriousSnow** [comment]
> @SeriousSnow 是不是发送的内容有问题， 我这边看不到

之前是通过邮件回复的 我来github回复了

这是第一个页面的 

fitSceneHeight===>>> 515.5555419921875 233
fitSceneHeight===>>> 924.7999877929688 925
fitSceneHeight===>>> 1242.6666259765625 925
fitSceneHeight===>>> 924.7999877929688 925

这是第二个页面的
fitSceneHeight===>>> 425.95556640625 333
fitSceneHeight===>>> 476.79998779296875 1101
fitSceneHeight===>>> 1100.800048828125 1101
fitSceneHeight===>>> 1100.800048828125 1101

**Comment by zyslife** [comment]
@SeriousSnow 你第一个页面切换第二个页面的时候有做什么操作吗？ 看起来整个组件的高度发生了变化，或者是header高度发生了变化吗?  能否提供一个简单的能复现的demo?

**Comment by SeriousSnow** [comment]
> @SeriousSnow 你第一个页面切换第二个页面的时候有做什么操作吗？ 看起来整个组件的高度发生了变化，或者是header高度发生了变化吗? 能否提供一个简单的能复现的demo?

这两个是不同的两个页面 都使用了这个插件，都是只能显示第一个flatlist，第二个flatlist 就是空白的 。要明天才能继续用别人的手机测试了

**Comment by zyslife** [comment]
@SeriousSnow 噢，是两个不同的页面那我就能理解了，明天有时间也最好能提供一个demo。

**Comment by SeriousSnow** [comment]
> @SeriousSnow 噢，是两个不同的页面那我就能理解了，明天有时间也最好能提供一个demo。
`import React, { Component } from "react";
import { View, FlatList, Text } from 'react-native';
import { HPageViewHoc } from 'react-native-head-tab-view'
import { CollapsibleHeaderTabView } from 'react-native-scrollable-tab-view-collapsible-header'


const HFlatList = HPageViewHoc(FlatList)

export default class Test extends Component {

    static navigationOptions = () => {
        return {
            headerTitle: "测试",
        };
    };

    state = {
        data1: [],
        data2: [],
    }

    componentDidMount() {
        this.getData1()
        this.getData2()
    }

    getData1 = () => {
        setTimeout(() => {
            this.setState({ data1: new Array(30).fill(1) })
        }, 500)
    }
    getData2 = () => {
        setTimeout(() => {
            this.setState({ data2: new Array(20).fill(2) })
        }, 600)
    }

    keyExtractor = (item, index) => {
        return `${index}`;
    }

    _renderSeparator() {
        return <View style={{ height: 1, backgroundColor: '#ECEDEF' }} />;
    }


    render() {
        return (
            <CollapsibleHeaderTabView makeHeaderHeight={() => 210}
                renderScrollHeader={() => <View
                    style={{ height: 200, backgroundColor: 'red', }}

                />}>
                <HFlatList index={0}
                    extraData={this.state}
                    keyboardShouldPersistTaps={'always'}
                    horizontal={false}
                    data={this.state.data1}
                    renderItem={({ item, index }) => {
                        return <View style={{ height: 30, justifyContent: 'center', alignItems: 'center' }}>
                            <Text>{item}</Text>
                        </View>
                    }}
                    initialNumToRender={10}
                    keyExtractor={this.keyExtractor}
                    showsVerticalScrollIndicator={false}
                    ItemSeparatorComponent={this._renderSeparator}
                    removeClippedSubviews={true}
                    windowSize={300}
                />
                <HFlatList index={1}
                    extraData={this.state}
                    keyboardShouldPersistTaps={'always'}
                    horizontal={false}
                    data={this.state.data2}
                    renderItem={({ item, index }) => {
                        return <View style={{ height: 30, justifyContent: 'center', alignItems: 'center' }}>
                            <Text>{item}</Text>
                        </View>
                    }}
                    initialNumToRender={10}
                    keyExtractor={this.keyExtractor}
                    showsVerticalScrollIndicator={false}
                    ItemSeparatorComponent={this._renderSeparator}
                    removeClippedSubviews={true}
                    windowSize={300}
                />
            </CollapsibleHeaderTabView>
        )
    }
}`

这是index文件
我发现了一个神奇的地方 如果data1的长度大于data2的长度，flatlist2就不会显示,否则就可以显示

**Comment by zyslife** [comment]
这个问题主要还是onLayout在不同手机上测量精度问题，我马上优化下 发布新的v3版本， 谢谢你配合  @SeriousSnow

**Comment by SeriousSnow** [comment]
> 这个问题主要还是onLayout在不同手机上测量精度问题，我马上优化下 发布新的v3版本， 谢谢你配合 @SeriousSnow

应该感谢的是我
发布后我会尽快测试的

**Comment by zyslife** [comment]
@SeriousSnow 试试 v3.0.5.

**Comment by SeriousSnow** [comment]
> @SeriousSnow 试试 v3.0.5.

目前可以了，非常感谢

**Comment by 276259822** [comment]
rc. 4版本没出现这个问题了，非常感谢
