### ISSUE TITLE
列表默认样式被覆盖

### ISSUE THREAD

**Issue by geng452654716** [zyslife/react-native-head-tab-view#83]
## Describe the bug
下方列表如果自己设置了 contentContainerStyle 样式，会把默认的 paddingTop 覆盖，导致内容被头部遮盖。
![image](https://user-images.githubusercontent.com/20813301/113803792-cf5c9200-978f-11eb-987e-7df617fcffe1.png)
### Expected behavior
合并自己的样式和默认样式
## Package versions  

- React Native: 0.64.0

**Comment by zyslife** [comment]
好的，会在下个版本更新

**Comment by zyslife** [comment]
@geng452654716 已经在rc. 4版本修复
