### ISSUE TITLE
试了很多次，无法运行

### ISSUE THREAD

**Issue by gerfisher** [zyslife/react-native-head-tab-view#86]
Running "oe" with {"rootTag":1,"initialProps":{}}
 ERROR  Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at App.js:9.
    in ExampleBasic (at renderApplication.js:47)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:107)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:134)
    in AppContainer (at renderApplication.js:40)
 ERROR  Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

import * as React from 'react';
import { View } from 'react-native';
import { HScrollView } from 'react-native-head-tab-view'
import { CollapsibleHeaderTabView } from 'react-native-scrollable-tab-view-collapsible-header'
export default class ExampleBasic extends React.PureComponent<any> {
    render() {
        return (
            <CollapsibleHeaderTabView renderScrollHeader={() => <View style={{ height: 200, backgroundColor: 'red' }} />}>
                <HScrollView index={0}>
                    <View style={{ height: 1000, backgroundColor: '#ff4081' }} />
                </HScrollView>
                <HScrollView index={1}>
                    <View style={{ height: 1000, backgroundColor: '#673ab7' }} />
                </HScrollView>
            </CollapsibleHeaderTabView>
        )
    }
}

这段代码无法运行

**Comment by HimiGame** [comment]
babel.config.js 文件中添加：

  plugins: ['react-native-reanimated/plugin'],

如下：
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
};


然后 
尝试清除缓存

npm start -- --reset-cache
or
yarn start --reset-cache

**Comment by zyslife** [comment]
@gerfisher 请问Example可以跑起来吗？

**Comment by gerfisher** [comment]
TypeError: renderTabViewContainer is not a function. (In 'renderTabViewContainer(containerProps)', 'renderTabViewContainer' is undefined)

**Comment by gerfisher** [comment]
是不是少安装了什么

**Comment by zyslife** [comment]
你的react-native-head-tab-view 是什么版本 @gerfisher

**Comment by gerfisher** [comment]
"react-native-scrollable-tab-view": "^1.0.0",
  "react-native-scrollable-tab-view-collapsible-header": "^2.0.1",


装的是这个

**Comment by gerfisher** [comment]
"react-native-head-tab-view": "^3.0.5",

**Comment by zyslife** [comment]
@gerfisher 

## Version

|       react-native-head-tab-view       |          react-native-scrollable-tab-view          |    react-native-tab-view-collapsible-header   |
| :--------------: | :--------------------: | :--------------------: |
| v1 ~ v2 | - | - |
|   v3   | v0 | v0 |
|   v4-rc.1   | v1 | v1 |
|   v4-rc.2   | v2 | v2 |

react-native-scrollable-tab-view-collapsible-header的版本错了，需要装v0的版本

**Comment by gerfisher** [comment]
多谢，我试试

**Comment by gerfisher** [comment]
TypeError: renderTabViewContainer is not a function. (In 'renderTabViewContainer(containerProps)', 'renderTabViewContainer' is undefined)

This error is located at:
    in GestureContainer (at createHeaderTabsComponent.tsx:48)
    in CollapsibleHeaderTabView (at createHeaderTabsComponent.tsx:15)
