### ISSUE TITLE
rendercene rerender too many times

### ISSUE THREAD

**Issue by surethink** [zyslife/react-native-head-tab-view#88]
## Describe the bug
render scene re render too many times
I need to pass params to child component, so not use scene map 

 LOG  2021-04-14T05:17:25.251Z parent component render
 LOG  2021-04-14T05:17:25.267Z render scene
 LOG  2021-04-14T05:17:25.421Z render scene
 LOG  2021-04-14T05:17:25.448Z render scene
 LOG  2021-04-14T05:17:25.470Z render scene
 LOG  2021-04-14T05:17:25.472Z render scene
 LOG  2021-04-14T05:17:25.514Z render scene
 LOG  2021-04-14T05:17:25.515Z render scene
 LOG  2021-04-14T05:17:25.531Z parent component render
 LOG  2021-04-14T05:17:25.537Z render scene
 LOG  2021-04-14T05:17:25.539Z render scene
 LOG  2021-04-14T05:17:25.562Z render scene
 LOG  2021-04-14T05:17:25.564Z render scene
 LOG  2021-04-14T05:17:25.596Z render scene
 LOG  2021-04-14T05:17:25.598Z render scene
 LOG  2021-04-14T05:17:25.621Z render scene
 LOG  2021-04-14T05:17:25.623Z render scene

### Expected behavior
render scene times as few as possible

## Package versions  
"react-native": "0.64.0",
"react-native-head-tab-view": "^4.0.0-rc.4",
"react-native-gesture-handler": "^1.10.3",

demo code:
1.parent.js

import React, { useState } from 'react';
import { Dimensions,View } from 'react-native';
import { CollapsibleHeaderTabView } from 'react-native-tab-view-collapsible-header'
import Child1Tab from './Child1'
import Child2Tab from './Child2'

export default function Parent({ route, navigation }) {
    const [index, setIndex] = useState(0);
    const [routes, setRoutes] = useState([
        { key: "child1", title: "child1" },
        { key: "child2", title: "child2" },
    ]);
    console.log(new Date(), "parent component render")
    const renderScene = ({ route }) => {
        console.log(new Date(), "render scene")
        switch (route.key) {
            case "child1":
                return (
                    <Child1Tab
                    />);
            case "child2":
                return (
                    <Child2Tab
                    />);
            default:
                return null;
        }
    };
    const [scrollHeaderHeight, setScrollHeaderHeight] = useState(12)
    const handleGetCardInfo = (event) => {
        const { height } = event.nativeEvent.layout
        setScrollHeaderHeight(height)
    }

    const renderScrollHeader = () => {
        return (
            <View
                onLayout={handleGetCardInfo}
            >
                <View style={{ height: 150, backgroundColor: "blue" }}>

                </View>
            </View>
        )
    }
    const initialLayout = { width: Dimensions.get('window').width };
    return (
        <View style={{ flex: 1 }}>
            <CollapsibleHeaderTabView
                headerHeight={scrollHeaderHeight}
                renderScrollHeader={renderScrollHeader}
                navigationState={{ index, routes }}
                renderScene={renderScene}
                onIndexChange={setIndex}
                initialLayout={initialLayout}
            />
        </View>
    )
}

2.child1.js

import React from 'react';
import { View ,Text} from 'react-native';
import { HScrollView } from 'react-native-head-tab-view'

export default function Child1Tab(props) {
    const arr = [1, 2, 3, 4, 5]
    return (
        <HScrollView index={0}>
            {arr.map((item,i) => {
                return (
                    <View style={{ height: 100,backgroundColor:"green"  }} key={i}>
                        <Text>{item}</Text>
                    </View>
                )
            })}
        </HScrollView>
    )
}

3.child2.js

import React from 'react';
import { View ,Text} from 'react-native';
import { HScrollView } from 'react-native-head-tab-view'

export default function Child2Tab(props) {
    const arr = [6, 7, 8, 9, 10]
    return (
        <HScrollView index={1}>
            {arr.map((item,i) => {
                return (
                    <View style={{ height: 100,backgroundColor:"red" }} key={i}>
                        <Text>{item}</Text>
                    </View>
                )
            })}
        </HScrollView>
    )
}

**Comment by zyslife** [comment]
@surethink Please make sure the demo is correct. I see many places are incomplete and report errors.

**Comment by surethink** [comment]
> @surethink Please make sure the demo is correct. I see many places are incomplete and report errors.

sorry for that, the code is edited, pls try again

**Comment by zyslife** [comment]
> I read the doc of react native tab view, which says:
"You need to make sure that your individual routes implement a shouldComponentUpdate to improve the performance."
Yes, that may be your problem.

```

switch (route.key) {
    case "child1":
        // Is this code right here?
        return (
);
    case "child2":
        return (
);
    default:
        return null;
}
};
```

Also, why don't I see HScrollView in child1.js and child1.js.

**Comment by surethink** [comment]
> > I read the doc of react native tab view, which says:
> > "You need to make sure that your individual routes implement a shouldComponentUpdate to improve the performance."
> 
> @surethink
> Yes, that may be your problem.
> 
> Also about your demo
> 
> ```
> 
> switch (route.key) {
>     case "child1":
>         // Is this code right here?
>         return (
> );
>     case "child2":
>         return (
> );
>     default:
>         return null;
> }
> };
> ```
> 
> Also, why don't I see HScrollView in child1.js and child1.js.

It's so strange!  
In edit status of my post,There exist  <HScrollView> and </HScrollView> in return statement below , just see the two empty lines 
When published, the tags are filtered out by github

    return (
        <HScrollView index={0}>
            {arr.map((item,i) => {
                return (
                    <View style={{ height: 100,backgroundColor:"green"  }} key={i}>
                        <Text>{item}</Text>
                    </View>
                )
            })}
        </HScrollView>
    )

**Comment by zyslife** [comment]
@surethink When first loaded, it is possible to render multiple times.
You can optimize it in two ways:
1. Set `lazy` to true for `react-native-tab-view` 
2. Double-wrap your Child so that its children become PureComponent.

**Comment by surethink** [comment]
> @surethink When first loaded, it is possible to render multiple times.
> You can optimize it in two ways:
> 
> 1. Set `lazy` to true for `react-native-tab-view`
> 2. Double-wrap your Child so that its children become PureComponent.

thanks!

**Comment by mengheangrat** [comment]
If anyone still faces this issue. let's follow my solution:

1. Create a separate to make index state to main tap only 
2. Pass some dynamic props to the custom tap component 
`
const initialLayout = { width: Dimensions.get('window').width }
const HeaderHeight = scale(185)

const MainTap = ({ renderScene, renderScrollHeader }) => {
  const [index, setIndex] = React.useState(0)
  const routes = [
    { key: 'first', title: 'Rewards' },
    { key: 'second', title: 'Menu' },
    { key: 'third', title: 'Info' },
  ]

  const MyTap = ({ props }) => (
    <TabBar
      indicatorStyle={{ backgroundColor: Colors.yellow }}
      style={{ backgroundColor: 'white' }}
      labelStyle={{ ...Fonts.style.description }}
      activeColor={Colors.black}
      inactiveColor={Colors.gray}
      indicatorContainerStyle={{
        borderBottomColor: Colors.lightGray,
        borderBottomWidth: 1,
        borderTopColor: Colors.lightestGray,
        borderTopWidth: 1,
      }}
      {...props}
    />
  )

  return (
    <CollapsibleHeaderTabView
      renderTabBar={(props) => <MyTap props={props} />}
      sceneContainerStyle={{ backgroundColor: 'white' }}
      renderScrollHeader={renderScrollHeader}
      navigationState={{ index, routes }}
      renderScene={renderScene}
      onIndexChange={setIndex}
      initialLayout={initialLayout}
      style={{ backgroundColor: 'white', flex: 1 }}
    />
  )
}`
