### ISSUE TITLE
重新渲染renderScrollHeader

### ISSUE THREAD

**Issue by xiaoxiaodemeng** [zyslife/react-native-head-tab-view#89]
我问一下你这边有考虑到renderScrollHeader作为一个组件 如果传入了参数有变化 要如何重新渲染

**Comment by zyslife** [comment]
@xiaoxiaodemeng   #72  只要保证参数变化时，整个组件有渲染就可以了，因为renderScrollHeader渲染出来的组件是在CollapsibleHeaderTabView的children中

**Comment by xiaoxiaodemeng** [comment]
所以是

> @xiaoxiaodemeng #72 只要保证参数变化时，整个组件有渲染就可以了，因为renderScrollHeader渲染出来的组件是在CollapsibleHeaderTabView的children中

你的意思是重新渲染整个 CollapsibleHeaderTabView组件是吧

**Comment by xiaoxiaodemeng** [comment]
> @xiaoxiaodemeng #72 只要保证参数变化时，整个组件有渲染就可以了，因为renderScrollHeader渲染出来的组件是在CollapsibleHeaderTabView的children中

我现在就是通过给CollapsibleHeaderTabView 组件一个key ,让他重新渲染一下，我也看了源码，似乎没有检测renderScrollHeader传参变化而部分重新渲染的操作

**Comment by xiaoxiaodemeng** [comment]
就一个状态就要去重新渲染整个CollapsibleHeaderTabView【其实就是一整个页面】有点得不偿失啊

**Comment by zyslife** [comment]
@xiaoxiaodemeng  其实不用过于担心，虽然渲染了CollapsibleHeaderTabView，但是它的子标签页没有重新渲染，所以影响不大。 这个就好比你封装了FlatList，然后你想要渲染它的头部，但是FlatList的render函数没有被执行的话， 头部也是不会刷新的。 你可以提出贴出现在遇到问题的简单的demo在这里，我们可以分析讨论一下

**Comment by xiaoxiaodemeng** [comment]
这块地方可以跟FlatList的ListHeaderComponent一样接收component类型就好了，让组件自己决定内部的更新,你这个地方只接受function有点限制渲染了

**Comment by xiaoxiaodemeng** [comment]
我去看了一下flatlist 组件的源码 ，他提供了一个属性 extraData ，然后回调给了头部组件  尾部组件 以及列表组件，可以模仿一下他的模式 https://github.com/facebook/react-native/blob/bac2c2c80158a654be947d43a3fbd75d5cb1395a/Libraries/Lists/VirtualizedList.js#L1163

**Comment by xiaoxiaodemeng** [comment]
我先自己改源码好了

**Comment by zyslife** [comment]
> 我先自己改源码好了

恩，我让renderScrollHeader也可以接受component类型吧

**Comment by xiaoxiaodemeng** [comment]
> > 我先自己改源码好了
> 
> 恩，我让renderScrollHeader也可以接受component类型吧

React.isValidElement 这个方法直接判断就好了
