### ISSUE TITLE
Error: If you want to use Reanimated 2 then go through our installation 

### ISSUE THREAD

**Issue by RedBull996** [zyslife/react-native-head-tab-view#91]
{        "react-native-head-tab-view": "4.0.0-rc.4",
        "react-native-reanimated": "^2.1.0",
        "react-native-safe-area-context": "^3.2.0",
        "react-native-scrollable-tab-view": "^1.0.0",
        "react-native-scrollable-tab-view-collapsible-header": "^2.0.1",
        "react": "17.0.1",
        "react-native": "0.64.0",
}

-----babel.config.js
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      "transform-inline-environment-variables"
    ],
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    [
      "@babel/plugin-transform-runtime",
      {
        "helpers": true,
        "regenerator": false
      }
    ],
    [
      "module-resolver",
      {
        "root": [
          "./"
        ],
        "alias": {
          "@": "./src",
          "json": "./src/json",
          "img": "./src/common/images",
          "components": "./src/components",
          "views": "./src/common/view"
        },
        "extensions": [
          ".js",
          ".ios.js",
          ".android.js"
        ]
      }
    ],
    'react-native-reanimated/plugin',
  ],
};

**Comment by RedBull996** [comment]
一直提示按官方的文档安装,但是我看不出来哪里不对,请帮忙看下

**Comment by RedBull996** [comment]
我这边ios是混合开发的，把demo里的工程放到我的RN工程/ios下是可以运行的，求指教

**Comment by zyslife** [comment]
@RedBull996 报错了提示什么呢
