### ISSUE TITLE
Feature Request: Snap support for Header

### ISSUE THREAD

**Issue by bikranttripathi** [zyslife/react-native-head-tab-view#92]
Hi @zyslife, I was hoping if we could add snap to collapsed state and expanded state if a user stops scrolling without fully collapsing or expanding the header kind of like in this gif below.

One possible solution could be adding an optional boolean props `snap` for `CollapsibleHeaderProps` and  when we detect if the user has stopped scrolling we snap them to the nearest state(Collapsed/Expanded) if the `snap` flag is turned on.

Please let me know what you think about this 😄 

![snap](https://user-images.githubusercontent.com/9078748/115611571-3f066d00-a2b8-11eb-9fea-e3f95d49b96a.gif)

**Comment by zyslife** [comment]
@bikranttripathi Thanks for the advice. It's a great idea. I'll start thinking about it and finish it.

**Comment by bikranttripathi** [comment]
@zyslife forgot to also add this as well. It will be great if the collapsed snap would also work with `frozeTop` props. 
For example: if I set `frozeTop=100`  then, the collapsed height will be `100` rather than 0, if we don't set it.

**Comment by zyslife** [comment]
> @zyslife forgot to also add this as well. It will be great if the collapsed snap would also work with `frozeTop` props. 
> 
> For example: if I set `frozeTop=100`  then, the collapsed height will be `100` rather than 0, if we don't set it.

Yes, that's the right way to think about it.

**Comment by zyslife** [comment]
@bikranttripathi Sorry to have kept you waiting, please check v4.0.0-rc5.

**Comment by bikranttripathi** [comment]
@zyslife This is amazing, thank you. I just tested the latest release `v4.0.0-rc5` and noticed that after scrolling from the header the snap effect isn't smooth and works inconsistently.

**Comment by zyslife** [comment]
@bikranttripathi  There are bugs in v4.0.0-rc5, please check v4.0.0-rc7.
Alternatively, you can adjust the value of the property `snapWaitDuration` to get a state that suits you better

**Comment by bikranttripathi** [comment]
Hi @zyslife , It doesn't seem like `v4.0.0-rc7` has been released yet.

**Comment by zyslife** [comment]
> Hi @zyslife , It doesn't seem like `v4.0.0-rc7` has been released yet.

Sorry, I forgot to post it, it's fine now.

**Comment by bikranttripathi** [comment]
Hi @zyslife, I updated to the latest version `v4.0.0-rc7` but I'm still experiencing issues when snapping by scrolling from the header. Scrolling from the scroll container `HScrollView` works great but scrolling from the `scrollHeader` doesn't fully snap to either collapsed or expanded state. 

I currently have `snapWaitDuration` set to `0` because I want it to snap to the nearest state as soon as the user stops scrolling. Could it be that there are two animation running at the same time? One that moves the scroll container's offset and snap animation, which could be causing this weird behavior?

I recorded a video of how it is currently working. I hope it helps in debugging why this is happening. 

Video Link: https://we.tl/t-WIGIvDlxko

Thank you.

**Comment by bikranttripathi** [comment]
Thank you so much @zyslife.

**Comment by zyslife** [comment]
@bikranttripathi I have released `v4.0.0-rc8`. I hope to solve this issue. In addition,  I deprecated the snapWaitDuration property and added the `scrollingCheckDuration ` property.`SnapWaitDuration` is now 0 by default. 
Thank you for your effort and cooperation.

**Comment by bikranttripathi** [comment]
Thank you @zyslife. `4.0.0-rc8` version is working great.
