### ISSUE TITLE
TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found

### ISSUE THREAD

**Issue by kea0811** [zyslife/react-native-head-tab-view#93]
## Describe the bug

I was trying with the example provided and this is what i met.

## Package versions  

-  "react": "^17.0.2"
- "react-native": "0.64.0"
- "react-native-gesture-handler": "^1.10.3"
- "react-native-head-tab-view": "^4.0.0-rc.0",
- "react-native-scrollable-tab-view-collapsible-header": "^1.0.0-rc3"

![Simulator Screen Shot - iPhone 11 - 2021-04-26 at 22 07 56](https://user-images.githubusercontent.com/8357167/116097339-a53a2800-a6dc-11eb-9ae0-c55988f28651.png)

const ScrollableTabViewContainer = props => {
    const [isRefreshing, setIsRefreshing] = useState(false);

    const _renderScrollHeader = () => (
      <ImageBackground
        source={restaurantImage}
        resizeMode="stretch"
        style={[styles.headerStyle, {
          height: 180
        }]}
      />
    );

    return (
      <CollapsibleHeaderTabView
        isRefreshing={isRefreshing}
        renderScrollHeader={_renderScrollHeader}
        {...props}
      >
        <View tabLabel="aaa" key="ScrollViewPage" index={0}>
          <Text>aaa</Text>
        </View>

        <View tabLabel="bbb" key="ScrollViewPage1" index={1}>
          <Text>bbb</Text>
        </View>

        <View tabLabel="ccc" key="ScrollViewPage2" index={2}>
          <Text>ccc</Text>
        </View>
      </CollapsibleHeaderTabView>
    );
  };

**Comment by zyslife** [comment]
https://github.com/software-mansion/react-native-reanimated/issues/1825
@kea0811
