### ISSUE TITLE
使用后提示TypeError: renderTabViewContainer is not a function。版本3.0.4。使用的函数组件

### ISSUE THREAD

**Issue by SummerHenry** [zyslife/react-native-head-tab-view#95]
## Describe the bug

TypeError: renderTabViewContainer is not a function. (In 'renderTabViewContainer(containerProps)', 'renderTabViewContainer' is undefined)

This error is located at:
    in GestureContainer (at createHeaderTabsComponent.tsx:48)
    in CollapsibleHeaderTabView (at createHeaderTabsComponent.tsx:15)
    in ForwardRef (at RadioScreenNew.js:109)
    in RCTView (at RadioScreenNew.js:108)
    in RadioScreenNew (at FindScreen.js:45)
    in StaticContainer (at SceneComponent.js:11)
    in RCTView (at SceneComponent.js:10)
    in SceneComponent (at react-native-scrollable-tab-view/index.js:283)
    in RCTScrollContentView (at ScrollView.js:1038)
    in RCTScrollView (at ScrollView.js:1178)
    in ScrollView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at react-native-scrollable-tab-view/index.js:228)
    in RCTView (at react-native-scrollable-tab-view/index.js:396)
    in ScrollableTabView (at FindScreen.js:26)
    in RCTSafeAreaView (at SafeAreaView.js:55)
    in SafeAreaView (at FindScreen.js:25)
    in Unknown (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at BottomTabView.tsx:55)
    in SceneContent (at BottomTabView.tsx:172)
    in RCTView (at ResourceSavingScene.tsx:68)
    in RCTView (at ResourceSavingScene.tsx:63)
    in ResourceSavingScene (at BottomTabView.tsx:166)
    in RCTView (at src/index.native.tsx:145)
    in ScreenContainer (at BottomTabView.tsx:146)
    in SafeAreaProviderCompat (at BottomTabView.tsx:145)
    in BottomTabView (at createBottomTabNavigator.tsx:45)
    in BottomTabNavigator (at TabNavigator.js:14)
    in TabNavigator (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at CardContainer.tsx:245)
    in RCTView (at CardContainer.tsx:244)
    in RCTView (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:573)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at Card.tsx:544)
    in RCTView (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:623)
    in RCTView (at Screens.tsx:84)
    in MaybeScreen (at CardStack.tsx:616)
    in RCTView (at Screens.tsx:54)
    in MaybeScreenContainer (at CardStack.tsx:498)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at MainStackNavigator.js:126)
    in MainStackNavigator (at RootScreen.js:44)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:409)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at RootScreen.js:38)
    in RootScreen (at App.js:43)
    in ChildrenWrapper (at wrapRootComponent.js:9)
    in _default (at wrapRootComponent.js:8)
    in Root (at RootSiblingsManager.js:75)
    in RootSiblingParent (at App.js:42)
    in PersistGate (at App.js:41)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at App.js:39)
    in Provider (at App.js:38)
    in App (at RootScreen.js:12)
    in RCTView (at RootScreen.js:11)
    in _class (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in ChildrenWrapper (at wrapRootComponent.js:9)
    in _default (at wrapRootComponent.js:8)
    in Root (at AppContainer.js:115)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

_renderTabViewContainer
    GestureContainer.tsx:137:42
render
    index.bundle?platform=ios&dev=true&minify=false:166136:40
renderRoot
    [native code]:0
runRootCallback
    [native code]:0
callFunctionReturnFlushedQueue
    [native code]:0

![image](https://user-images.githubusercontent.com/17306914/118073270-19afdf00-b3de-11eb-827e-95c470e7a94f.png)

![image](https://user-images.githubusercontent.com/17306914/118073322-2df3dc00-b3de-11eb-910c-ac8f037f17e4.png)
期待回复额。

## Package versions  

- React: 16.9.0
- React Native: 0.61.4
- React-Native-Gesture-Handler 1.8.0

**Comment by zyslife** [comment]
@SummerHenry 应该是使用的是版本错了

## Version

| react-native-head-tab-view | react-native-scrollable-tab-view | react-native-tab-view-collapsible-header |
| :------------------------: | :------------------------------: | :--------------------------------------: |
|          v1 ~ v2           |                -                 |                    -                     |
|             v3             |                v0                |                    v0                    |
|          v4-rc.1           |                v1                |                    v1                    |
|          v4-rc.2~          |                v2                |                    v2                    |

**Comment by SummerHenry** [comment]
> @SummerHenry应该是使用的是版本错了
> 
> ## 版本
> react-native-head-tab-view	react-native-scrollable-tab-view	反应本机选项卡视图可折叠标头
> v1〜v2	--	--
> v3	v0	v0
> v4-rc.1	v1	v1
> v4-rc.2〜	v2	v2

react-native-head-tab-view 是3.0.4的。react-native-scrollable-tab-view是1.0,0的。
现在有出现了个新问题: HPageViewHoc: index must not be undefined

**Comment by zyslife** [comment]
@SummerHenry 不好意思，是我的文档写错了。
## Version

| react-native-head-tab-view | react-native-scrollable-tab-view-collapsible-header | react-native-tab-view-collapsible-header |
| :------------------------: | :-------------------------------------------------: | :--------------------------------------: |
|          v1 ~ v2           |                          -                          |                    -                     |
|             v3             |                         v0                          |                    v0                    |
|          v4-rc.1           |                         v1                          |                    v1                    |
|          v4-rc.2~          |                         v2                          |                    v2                    |

和react-native-scrollable-tab-view版本没有关系，只和react-native-scrollable-tab-view-collapsible-header版本有关系.
