### ISSUE TITLE
renderRefreshControl  progress value not change when pull down

### ISSUE THREAD

**Issue by surethink** [zyslife/react-native-head-tab-view#98]
## Describe the bug
When I render custom refresh control with renderRefreshControl,  progress value is 0, not change during pull down, when stop, the value is 1

`
    const renderRefreshControl = ({ refreshValue, refreshType, progress }) => {
        console.log(refreshValue, refreshType, progress)
        return (
            <View style={{backgroundColor:"red",alignItems:"center",paddingVertical:0}}>
                <ActivityIndicator size="small" color={colors.secondaryTextColor} />
                <Text>{progress.value}</Text>
            </View>
        )
    }
`
### Expected behavior
1、during pull down, progress value change from 1% to 100%
2、it's better that  there is no default distance between the custom refresh control view and my screen view.

## Package versions  

![未命名](https://user-images.githubusercontent.com/23416921/118347985-c96d8400-b579-11eb-834d-1c063216631f.png)

- React: 17.0.2
- React Native: 0.64
- React-Native-Gesture-Handler: ^1.10.3

**Comment by zyslife** [comment]
@surethink Because progress is Reanimated2.SharedValue , it should be used like this.

```
useAnimatedReaction(() => {
    return progress
}, () => {
    console.log(progress.value);
})

useDerivedValue(()=>{
    console.log(progress.value);
})
```

**Comment by zyslife** [comment]
You can refer to the `CustomRefreshControl` file in the example.

**Comment by surethink** [comment]
> You can refer to the `CustomRefreshControl` file in the example.

got it, thanks
